Repository team-aliens/DMS-Backend, pull requests merged in 2022-12, with the labels that each got.

#146 merge: (#145) 유효성 검사 에러 핸들링 추가
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/error/ErrorResponse.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/error/GlobalErrorHandler.kt
Labels: feat

#147 merge: 커스텀 타입의 @NotNull 필드 nullable 필드로 변경
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/auth/dto/request/CertifyEmailCodeWebRequest.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/manager/ManagerWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/manager/dto/request/GetStudentListWebRequest.kt
Labels: 👾bug

#149 merge: (#148) 관리자 토큰으로 학교 구분하기
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/spi/ManagerQueryStudentPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/usecase/QueryStudentDetailsUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/usecase/QueryStudentsUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/manager/usecase/QueryStudentDetailsUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/manager/usecase/QueryStudentsUseCaseTests.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/point/PointPersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
Labels: 👾bug

#150 merge: (#127) 상벌점 점수에 따른 랜덤 문구 반환
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/spi/PhrasePort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/spi/StudentQueryPhrasePort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/usecase/StudentMyPageUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/student/usecase/StudentMyPageUseCaseTests.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/point/model/Phrase.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/point/PhrasePersistenceAdapterStudent.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/point/entity/PhraseJpaEntity.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/point/repository/PhraseJpaRepository.kt
Labels: feat

#155 merge: (#154) 비밀번호 관련 요청 버그
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/manager/ManagerWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/manager/dto/request/Password.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/manager/dto/request/ResetPasswordManagerWebRequest.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/student/StudentWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/student/dto/request/ResetStudentPasswordWebRequest.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/student/dto/request/SignUpWebRequest.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/user/UserWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/user/dto/request/UpdateUserPasswordWebRequest.kt
Labels: 👾bug

#158 merge: (#157) 유효성 검사 수정
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/auth/AuthWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/auth/dto/request/CertifyEmailCodeWebRequest.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/auth/dto/request/CertifyEmailWebRequest.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/auth/dto/request/SendEmailCodeWebRequest.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/auth/dto/request/SignInWebRequest.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/file/FileWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/manager/ManagerWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/manager/dto/request/GetStudentListWebRequest.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/manager/dto/request/ResetPasswordManagerWebRequest.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/meal/MealWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/notice/NoticeWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/notice/dto/request/PostNoticeWebRequest.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/notice/dto/request/UpdateNoticeWebRequest.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/point/PointWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/school/SchoolWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/school/dto/request/UpdateQuestionWebRequest.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/student/StudentWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/student/dto/request/CheckStudentGcnWebRequest.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/student/dto/request/FindStudentAccountIdWebRequest.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/student/dto/request/ResetStudentPasswordWebRequest.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/student/dto/request/SignUpWebRequest.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/student/dto/request/UpdateStudentProfileWebRequest.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/user/UserWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/user/dto/request/UpdateUserPasswordWebRequest.kt
Labels: refactor

#161 merge: (#160) 공지사항 생성, 수정 완료 시 ID 반환하기
  dms-application/src/main/kotlin/team/aliens/dms/domain/notice/usecase/CreateNoticeUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/notice/usecase/UpdateNoticeUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/notice/usecase/CreateNoticeUseCaseTest.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/notice/usecase/UpdateNoticeUseCaseTest.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/notice/NoticeWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/notice/dto/response/CreateNoticeResponse.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/notice/dto/response/UpdateNoticeResponse.kt
Labels: feat

#165 merge: (#164) 학생 검증 테이블 재설계
  dms-domain/src/main/kotlin/team/aliens/dms/domain/student/model/VerifiedStudent.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/token/GenerateJwtAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/auth/entity/AuthCodeEntity.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/auth/entity/AuthCodeLimitEntity.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/auth/entity/RefreshTokenEntity.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/auth/mapper/AuthCodeLimitMapper.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/auth/mapper/AuthCodeMapper.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/auth/mapper/RefreshTokenMapper.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/auth/repository/AuthCodeEntityRepository.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/auth/repository/AuthCodeLimitRepository.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/auth/repository/RefreshTokenRepository.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/entity/VerifiedStudentEntity.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/entity/VerifiedStudentJpaEntity.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/mapper/VerifiedStudentMapper.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/repository/VerifiedStudentJpaRepository.kt
Labels: refactor

#168 merge: (#167) AuthCodeLimit 매번 새로운 UUID 저장됨
  dms-application/src/main/kotlin/team/aliens/dms/domain/auth/exception/AuthCodeLimitNotFoundException.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/auth/usecase/CertifyEmailCodeUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/auth/usecase/CertifyEmailCodeUseCaseTests.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/auth/error/AuthErrorCode.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/auth/model/AuthCodeLimit.kt
Labels: 👾bug

#170 merge: (#169) 자습실 & 자습실 신청 시간 엔티티 세팅
  dms-domain/src/main/kotlin/team/aliens/dms/domain/student/model/Sex.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/studyroom/error/.gitkeep
  dms-domain/src/main/kotlin/team/aliens/dms/domain/studyroom/exception/.gitkeep
  dms-domain/src/main/kotlin/team/aliens/dms/domain/studyroom/model/StudyRoom.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/studyroom/model/StudyRoomAvailableTime.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/studyroom/service/.gitkeep
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/entity/StudyRoomAvailableTimeJpaEntity.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/entity/StudyRoomJpaEntity.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/mapper/StudyRoomAvailableTimeMapper.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/mapper/StudyRoomMapper.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/repository/StudyRoomAvailableTimeJpaRepository.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/repository/StudyRoomJpaRepository.kt
Labels: setting

#173 merge: (#171) redis readonly replica 오류 해결
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/config/RedisConfig.kt
  dms-infrastructure/src/main/resources/application.yml
Labels: 👾bug

#174 merge: (#172) 자리 & 종류 엔티티 세팅
  dms-domain/src/main/kotlin/team/aliens/dms/domain/studyroom/model/Seat.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/studyroom/model/SeatStatus.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/studyroom/model/SeatType.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/entity/SeatJpaEntity.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/entity/SeatTypeJpaEntity.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/mapper/SeatMapper.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/mapper/SeatTypeMapper.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/repository/SeatJpaRepository.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/repository/SeatTypeJpaRepository.kt
Labels: setting

#181 merge: (#179) 자습실 신청 시간 설정 API
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/UpdateAvailableTimeUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/CommandAvailableTimePort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/StudyRoomAvailableTimePort.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/StudyRoomAvailableTimePersistenceAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/StudyRoomWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/UpdateAvailableTimeWebRequest.kt
Labels: feat

#184 merge: (#178) 자리 종류 보기 API
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/QuerySeatTypesResponse.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/QuerySeatTypePort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/SeatTypePort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/QueryAvailableTimeUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/QuerySeatTypesUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/UpdateAvailableTimeUseCase.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/studyroom/model/SeatType.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/SeatTypePersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/entity/SeatTypeJpaEntity.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/mapper/SeatTypeMapper.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/repository/SeatTypeJpaRepository.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/StudyRoomWebAdapter.kt
Labels: feat

#189 merge: (#188) stage 배포 시 healthcheck 기능 추가
  .github/workflows/stage-cd.yml
  Dockerfile
Labels: refactor

#190 merge: (#185) 자리 종류 생성 API
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/exception/SeatTypeAlreadyExistsException.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/CommandSeatTypePort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/QuerySeatTypePort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/SeatTypePort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/CreateSeatTypeUseCase.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/studyroom/error/SeatTypeErrorCode.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/SeatTypePersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/repository/SeatTypeJpaRepository.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/StudyRoomWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/CreateSeatTypeWebRequest.kt
Labels: feat

#193 merge: (#191) 자습실 자리 신청 API
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/exception/SeatAlreadyAppliedException.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/exception/SeatNotFoundException.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/exception/StudyRoomNotFoundException.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/CommandStudyRoomPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/QueryStudyRoomPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/StudyRoomPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/ApplySeatUseCase.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/studyroom/error/SeatErrorCode.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/studyroom/error/StudyRoomErrorCode.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/StudyRoomPersistenceAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/StudyRoomWebAdapter.kt
Labels: feat

#195 merge: (#194) 자습실 자리 신청 취소 API
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/QueryStudyRoomPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/UnApplySeatUseCase.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/StudyRoomPersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/repository/SeatJpaRepository.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/StudyRoomWebAdapter.kt
Labels: feat

#201 merge: (#182) 자습실 생성 API
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/CreateStudyRoomRequest.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/exception/StudyRoomAlreadyExistsException.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/CommandStudyRoomPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/QueryStudyRoomPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/CreateStudyRoomUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/studyroom/usecase/CreateStudyRoomUseCaseTests.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/studyroom/error/StudyRoomErrorCode.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/StudyRoomPersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/entity/SeatJpaEntity.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/repository/StudyRoomJpaRepository.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/StudyRoomWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/CreateStudyRoomResponse.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/CreateStudyRoomWebRequest.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/WebSeatStatus.kt
Labels: feat

#200 merge: (#199) 자습실 신청 & 취소 로직 추가 설계
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/exception/AppliedSeatNotFound.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/exception/SeatCanNotAppliedException.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/ApplySeatUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/UnApplySeatUseCase.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/studyroom/error/SeatErrorCode.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/studyroom/model/StudyRoom.kt
Labels: feat

#198 merge: (#196) 자습실 상세 보기 학생 API
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/StudentQueryStudyRoomResponse.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/QueryStudyRoomPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/vo/SeatVO.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/StudentQueryStudyRoomUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/studyroom/usecase/StudentQueryStudyRoomUseCaseTests.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/StudyRoomPersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/repository/vo/QuerySeatVO.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/StudyRoomWebAdapter.kt
Labels: feat

#205 merge: (#187) 자습실 삭제 API
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/CommandStudyRoomPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/RemoveStudyRoomUseCase.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/StudyRoomPersistenceAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/StudyRoomWebAdapter.kt
Labels: feat

#206 merge: (#204) 자습실 목록 보기 학생 API
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/StudentQueryStudyRoomsResponse.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/QueryStudyRoomPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/vo/StudyRoomVO.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/StudentQueryStudyRoomsUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/studyroom/usecase/StudentQueryStudyRoomsUseCaseTests.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/StudyRoomPersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/repository/SeatJpaRepository.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/repository/vo/QueryStudyRoomVO.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/StudyRoomWebAdapter.kt
Labels: feat

#212 merge: (#210) 자습실 신청, 취소 비즈니스 로직 수정
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/ApplySeatUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/UnApplySeatUseCase.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/studyroom/model/Seat.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/studyroom/model/StudyRoom.kt
Labels: feat

#211 merge: (#209) 자리 종류 삭제 API
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/exception/SeatTypeInUseException.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/exception/SeatTypeNotFoundException.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/CommandSeatTypePort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/QuerySeatTypePort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/SeatTypeQueryStudyRoomPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/StudyRoomPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/RemoveSeatTypeUseCase.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/studyroom/error/SeatTypeErrorCode.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/SeatTypePersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/StudyRoomPersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/repository/SeatJpaRepository.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/StudyRoomWebAdapter.kt
Labels: feat

#214 merge: 자습실 자리 신청 API 학년 & 성별 검사 추가
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/spi/StudentPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/exception/StudyRoomAvailableGradeMismatchException.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/exception/StudyRoomAvailableSexMismatchException.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/StudyRoomQueryStudentPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/ApplySeatUseCase.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/studyroom/error/StudyRoomErrorCode.kt
Labels: feat

#216 merge: (#215) 모든 Web 요청 Validation 추가
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/CreateStudyRoomRequest.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/UpdateStudyRoomRequest.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/auth/AuthWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/auth/dto/request/SendEmailCodeWebRequest.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/auth/dto/request/SignInWebRequest.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/auth/dto/request/WebEmailType.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/manager/dto/request/ResetPasswordManagerWebRequest.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/notice/NoticeWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/notice/dto/request/CreateNoticeWebRequest.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/notice/dto/request/UpdateNoticeWebRequest.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/notice/dto/request/WebOrderType.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/school/dto/request/UpdateQuestionWebRequest.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/student/dto/request/ResetStudentPasswordWebRequest.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/student/dto/request/SignUpWebRequest.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/student/dto/request/UpdateStudentProfileWebRequest.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/StudyRoomWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/CreateSeatTypeWebRequest.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/CreateStudyRoomWebRequest.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/UpdateStudyRoomWebRequest.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/WebSex.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/user/dto/request/UpdateUserPasswordWebRequest.kt
Labels: feat
