Repository team-aliens/DMS-Backend, pull requests merged in 2022-11, with the labels that each got.

#78 merge: (#76) 학번 검사 API
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/dto/CheckStudentGcnRequest.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/spi/StudentQuerySchoolPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/usecase/CheckStudentGcnUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/student/usecase/CheckStudentGcnUseCaseTests.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/auth/AuthWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/file/FileWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/manager/ManagerWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/notice/NoticeWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/school/SchoolWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/student/StudentWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/student/dto/request/CheckStudentGcnWebRequest.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/student/dto/response/CheckStudentGcnResponse.kt
Labels: feat

#80 merge: (#79) remove notice api
  dms-application/src/main/kotlin/team/aliens/dms/common/spi/SecurityPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/notice/exception/.gitkeep
  dms-application/src/main/kotlin/team/aliens/dms/domain/notice/exception/IsNotWriterException.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/notice/exception/NoticeNotFoundException.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/notice/spi/CommandNoticePort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/notice/spi/NoticePort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/notice/spi/NoticeSecurityPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/notice/spi/QueryNoticePort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/notice/usecase/RemoveNoticeUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/notice/usecase/RemoveNoticeUseCaseTests.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/notice/error/.gitkeep
  dms-domain/src/main/kotlin/team/aliens/dms/domain/notice/error/NoticeErrorCode.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/notice/NoticePersistenceAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/notice/NoticeWebAdapter.kt
Labels: feat

#82 merge: (#81) 공지사항 상세확인 API
  dms-application/src/main/kotlin/team/aliens/dms/domain/notice/dto/.gitkeep
  dms-application/src/main/kotlin/team/aliens/dms/domain/notice/dto/QueryNoticeDetailsResponse.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/notice/spi/NoticeQueryUserPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/notice/usecase/QueryNoticeDetailsUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/school/exception/SchoolMismatchException.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/user/spi/UserPort.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/notice/usecase/QueryNoticeDetailsUseCaseTests.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/school/error/SchoolErrorCode.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/meal/MealWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/notice/NoticeWebAdapter.kt
Labels: feat

#84 merge: (#83) 공지사항 목록 확인 API
  dms-application/src/main/kotlin/team/aliens/dms/domain/meal/dto/QueryMealsResponse.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/meal/usecase/QueryMealsUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/notice/dto/QueryAllNoticesResponse.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/notice/spi/QueryNoticePort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/notice/usecase/QueryAllNoticesUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/meal/usecase/QueryMealsUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/notice/usecase/QueryAllNoticesUseCaseTests.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/notice/model/OrderType.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/notice/NoticePersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/notice/repository/NoticeJpaRepository.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/notice/NoticeWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/notice/dto/request/.gitkeep
  dms-presentation/src/main/kotlin/team/aliens/dms/notice/dto/request/OrderType.kt
Labels: feat

#90 merge: (#89) 급식 엔티티 칼로리 정보 컬럼 추가
  dms-application/src/main/kotlin/team/aliens/dms/domain/meal/dto/QueryMealsResponse.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/meal/usecase/QueryMealsUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/meal/usecase/QueryMealsUseCaseTests.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/meal/model/Meal.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/meal/entity/MealJpaEntity.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/meal/mapper/MealMapper.kt
Labels: performance

#91 Revert "merge: (#89) 급식 엔티티 칼로리 정보 컬럼 추가"
  dms-application/src/main/kotlin/team/aliens/dms/domain/meal/dto/QueryMealsResponse.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/meal/usecase/QueryMealsUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/meal/usecase/QueryMealsUseCaseTests.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/meal/model/Meal.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/meal/entity/MealJpaEntity.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/meal/mapper/MealMapper.kt
Labels: performance

#86 merge: (#85) 공지사항 생성
  dms-application/src/main/kotlin/team/aliens/dms/domain/notice/spi/CommandNoticePort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/notice/usecase/CreateNoticeUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/notice/usecase/CreateNoticeUseCaseTest.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/notice/NoticePersistenceAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/notice/NoticeWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/notice/dto/request/PostNoticeWebRequest.kt
Labels: feat

#92 merge: security & exception filtering
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/filter/ExceptionFilter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/filter/JwtFilter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/CustomAccessDeniedHandler.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/CustomAuthenticationEntryPoint.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/error/SecurityErrorCode.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/exception/ForbiddenException.kt
Labels: 👾bug, refactor

#93 merge: (#72) stage cd
  .github/workflows/CI.yml
  .github/workflows/build.yml
  .github/workflows/stage-cd.yml
  Dockerfile
Labels: feat

#73 merge: (#71) 학생 상세조회 api
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/DependencyVersions.kt
  dms-application/src/main/kotlin/team/aliens/dms/common/spi/CoveredEmailPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/common/spi/ReceiveRandomStringPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/common/util/StringUtil.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/auth/usecase/CheckAccountIdExistenceUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/auth/usecase/SendEmailCodeUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/dto/GetStudentDetailsResponse.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/spi/ManagerQueryPointHistoryPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/spi/ManagerQueryStudentPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/spi/ManagerQueryUserPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/usecase/FindManagerAccountIdUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/usecase/GetStudentDetailsUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/spi/PointHistoryPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/spi/StudentPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/usecase/FindStudentAccountIdUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/auth/usecase/CheckAccountIdExistenceUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/auth/usecase/SendEmailCodeUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/manager/usecase/FindManagerAccountIdUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/manager/usecase/GetStudentDetailsUseCaseTest.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/student/usecase/FindStudentAccountIdUseCaseTests.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/point/model/PointOption.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/point/model/PointType.kt
  dms-infrastructure/build.gradle.kts
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/config/QueryDslConfig.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/point/PointHistoryPersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/point/entity/PointOptionJpaEntity.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/point/mapper/PointOptionMapper.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/user/UserPersistenceAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/manager/ManagerWebAdapter.kt
Labels: feat

#74 merge: (#70) 학생 목록 검색
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/dto/QueryStudentListResponse.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/dto/Sort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/spi/ManagerQueryUserPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/usecase/GetStudentListUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/manager/usecase/GetStudentListUseCaseTest.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/user/UserPersistenceAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/manager/ManagerWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/manager/dto/request/GetStudentListWebRequest.kt
Labels: feat

#94 merge: (#75) 학생 삭제 API
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/spi/ManagerCommandStudentPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/usecase/RemoveStudentUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/spi/StudentPort.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/manager/usecase/RemoveStudentUseCaseTests.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/user/UserPersistenceAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/manager/ManagerWebAdapter.kt
Labels: feat

#100 merge: (#96) 프로필 수정 API
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/spi/StudentSecurityPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/usecase/UpdateStudentProfileUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/student/usecase/UpdateStudentProfileUseCaseTests.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/student/StudentWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/student/dto/request/UpdateStudentProfileWebRequest.kt
Labels: feat

#99 merge: (#97) 비밀번호 수정 API
  dms-application/src/main/kotlin/team/aliens/dms/common/spi/SecurityPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/user/dto/.gitkeep
  dms-application/src/main/kotlin/team/aliens/dms/domain/user/dto/UpdateUserPasswordRequest.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/user/spi/CommandUserPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/user/spi/QueryUserPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/user/spi/UserPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/user/spi/UserSecurityPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/user/usecase/.gitkeep
  dms-application/src/main/kotlin/team/aliens/dms/domain/user/usecase/UpdateUserPasswordUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/user/usecase/UpdateUserPasswordUseCaseTests.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/user/.gitkeep
  dms-presentation/src/main/kotlin/team/aliens/dms/user/UserWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/user/dto/request/.gitkeep
  dms-presentation/src/main/kotlin/team/aliens/dms/user/dto/request/UpdateUserPasswordWebRequest.kt
Labels: feat

#98 merge: (#95) 마이페이지 확인 API
  dms-application/src/main/kotlin/team/aliens/dms/common/util/StringUtil.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/usecase/GetStudentDetailsUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/usecase/GetStudentListUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/spi/PointHistoryPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/dto/StudentMyPageResponse.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/spi/QueryStudentPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/spi/StudentQueryPointHistoryPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/usecase/StudentMyPageUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/manager/usecase/GetStudentDetailsUseCaseTest.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/manager/usecase/GetStudentListUseCaseTest.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/student/usecase/StudentMyPageUseCaseTests.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/student/model/Student.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/student/StudentWebAdapter.kt
Labels: feat

#108 merge: (#101) 확인질문 설정 API
  dms-application/src/main/kotlin/team/aliens/dms/common/spi/SecurityPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/school/dto/UpdateQuestionRequest.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/school/spi/CommandSchoolPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/school/spi/SchoolPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/school/spi/SchoolQueryUserPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/school/spi/SchoolSecurityPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/school/usecase/UpdateQuestionUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/user/spi/UserPort.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/school/usecase/UpdateQuestionUseCaseTests.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/school/SchoolPersistenceAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/school/SchoolWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/school/dto/request/.gitkeep
  dms-presentation/src/main/kotlin/team/aliens/dms/school/dto/request/UpdateQuestionWebRequest.kt
Labels: feat

#106 merge: (#105) 비밀번호 비교 API
  dms-application/src/main/kotlin/team/aliens/dms/domain/user/usecase/UserPasswordCompareUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/user/usecase/UserPasswordCompareUseCaseTests.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/user/UserWebAdapter.kt
Labels: feat

#110 merge: (#102) 상벌점 목록 확인 API
  dms-application/src/main/kotlin/team/aliens/dms/common/spi/SecurityPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/spi/ManagerQueryPointPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/usecase/GetStudentDetailsUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/dto/PointRequestType.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/dto/QueryPointHistoryResponse.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/exception/.gitkeep
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/spi/PointHistoryPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/spi/PointPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/spi/PointQueryUserPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/spi/PointSecurityPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/spi/QueryPointPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/usecase/QueryPointHistoryUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/spi/StudentQueryPointPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/usecase/StudentMyPageUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/user/spi/UserPort.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/manager/usecase/GetStudentDetailsUseCaseTest.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/point.usecase/QueryPointHistoryUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/student/usecase/StudentMyPageUseCaseTests.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/point/PointHistoryPersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/point/PointPersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/point/repository/vo/QueryPointHistoryVO.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/point/PointWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/point/dto/response/.gitkeep
Labels: feat

#109 merge: (#107) 학교 확인코드 재발급 API
  dms-application/src/main/kotlin/team/aliens/dms/domain/school/usecase/ReissueSchoolCodeUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/school/usecase/ReissueSchoolCodeUseCaseTests.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/school/SchoolWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/school/dto/response/ReissueSchoolCodeResponse.kt
Labels: feat

#113 merge: (#112) ses template api
  buildSrc/src/main/kotlin/Dependencies.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/template/spi/TemplatePort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/template/usecase/TemplateUseCase.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/auth/model/EmailType.kt
  dms-infrastructure/build.gradle.kts
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/error/GlobalErrorCode.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/email/AwsSESAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/email/AwsSesConfig.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/email/exception/SesException.kt
  dms-infrastructure/src/main/resources/application.yml
  dms-infrastructure/src/main/resources/templates/signup_template.html
  dms-presentation/src/main/kotlin/team/aliens/dms/template/EmailTemplateWebAdapter.kt
Labels: feat

#118 merge: (#117) UseCase 로직 검토
  dms-application/src/main/kotlin/team/aliens/dms/domain/auth/usecase/SignInUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/dto/QueryStudentsResponse.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/spi/ManagerPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/spi/QueryManagerPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/usecase/FindManagerAccountIdUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/usecase/ManagerMyPageUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/usecase/QueryStudentDetailsUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/usecase/QueryStudentsUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/usecase/RemoveStudentUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/usecase/ResetManagerPasswordUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/notice/usecase/CreateNoticeUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/notice/usecase/RemoveNoticeUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/notice/usecase/UpdateNoticeUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/usecase/QueryPointHistoryUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/usecase/StudentMyPageUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/usecase/UpdateStudentProfileUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/user/dto/UpdateUserPasswordRequest.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/user/exception/InvalidRoleException.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/user/usecase/UpdateUserPasswordUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/auth/usecase/SignInUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/manager/usecase/FindManagerAccountIdUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/manager/usecase/ManagerMyPageUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/manager/usecase/QueryStudentsUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/manager/usecase/ResetManagerPasswordUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/point.usecase/QueryPointHistoryUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/student/usecase/UpdateStudentProfileUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/user/usecase/UpdateUserPasswordUseCaseTests.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/student/model/Student.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/user/error/UserErrorCode.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/manager/ManagerPersistenceAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/manager/ManagerWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/user/UserWebAdapter.kt
Labels: refactor

#120 merge: (#119) Neis 학교 정보 엔티티 세팅
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/school/entity/NeisSchoolInfoJpaEntity.kt
Labels: setting

#121 merge: 이름 & 주소 Unique 컬럼 설정
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/school/entity/SchoolJpaEntity.kt
Labels: 👾bug

#123 merge: (#122) Neis 학교 정보 엔티티 제거
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/school/entity/NeisSchoolInfoJpaEntity.kt
Labels: 👾bug

#125 merge: (#124) QueryString Snake Case로 변경
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/notice/NoticeWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/school/SchoolWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/student/StudentWebAdapter.kt
Labels: 👾bug

#126 merge: Authority Number 에러
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/token/JwtParser.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/user/entity/UserJpaEntity.kt
Labels: 👾bug

#129 merge: (#128) Modelattribute Validation 에러
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/auth/AuthWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/auth/dto/request/CertifyEmailCodeWebRequest.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/auth/dto/request/CertifyEmailWebRequest.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/student/StudentWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/student/dto/request/CheckStudentGcnWebRequest.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/student/dto/request/FindStudentAccountIdWebRequest.kt
Labels: 👾bug

#131 merge: (#13) find manager account id usecase
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/spi/ManagerQueryUserPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/usecase/FindManagerAccountIdUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/manager/usecase/FindManagerAccountIdUseCaseTests.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/user/UserPersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/user/repository/UserJpaRepository.kt
Labels: 👾bug

#132 merge: (#133) 토큰 인증 오류 해결
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/filter/JwtFilter.kt
Labels: 👾bug

#135 merge: (#134) 학생 검색 API 버그
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/spi/ManagerQueryStudentPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/usecase/QueryStudentsUseCase.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/manager/ManagerWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/manager/dto/request/GetStudentListWebRequest.kt
Labels: 👾bug

#136 merge: 학교 이름 컬럼 변경
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/school/entity/SchoolJpaEntity.kt
Labels: 👾bug

#137 merge: 공지 목록 확인 API 버그
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/notice/NoticeWebAdapter.kt
Labels: 👾bug

#138 merge: 급식 날짜 Format
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/meal/MealWebAdapter.kt
Labels: 👾bug

#140 merge: (#139) Refresh Token 만료시간 추가
  dms-application/src/main/kotlin/team/aliens/dms/domain/auth/dto/ReissueResponse.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/auth/dto/SignInResponse.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/auth/dto/TokenResponse.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/auth/usecase/ReissueTokenUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/auth/usecase/SignInUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/dto/SignUpResponse.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/usecase/SignUpUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/auth/usecase/ReissueTokenUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/auth/usecase/SignInUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/student/usecase/SignUpUseCaseTests.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityProperties.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/token/GenerateJwtAdapter.kt
Labels: feat

#142 merge: (#141) 급식 조회 API 변경
  dms-application/src/main/kotlin/team/aliens/dms/common/extension/LocalDateExtension.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/meal/dto/QueryMealsResponse.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/meal/spi/QueryMealPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/meal/usecase/QueryMealsUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/meal/usecase/QueryMealsUseCaseTests.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/meal/MealPersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/meal/repository/MealJpaRepository.kt
Labels: 👾bug

#144 merge: (#143) PATCH 메소드 CORS 발생
  dms-presentation/src/main/kotlin/team/aliens/dms/common/WebMvcConfig.kt
Labels: 👾bug
