Repository team-aliens/DMS-Backend, pull requests merged in 2022-10, with the labels that each got.

#4 merge: (#3) Exception 세팅
  dms-domain/src/main/kotlin/team/aliens/dms/global/error/.gitkeep
  dms-domain/src/main/kotlin/team/aliens/dms/global/error/DmsException.kt
  dms-domain/src/main/kotlin/team/aliens/dms/global/error/ErrorProperty.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/error/.gitkeep
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/error/ErrorResponse.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/error/GlobalErrorCode.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/error/GlobalErrorHandler.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/exception/.gitkeep
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/exception/InternalServerErrorException.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/filter/.gitkeep
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/filter/ExceptionFilter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/filter/FilterConfig.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
Labels: setting

#11 merge: (#6) NoSQL Entity
  dms-domain/src/main/kotlin/team/aliens/dms/domain/auth/error/.gitkeep
  dms-domain/src/main/kotlin/team/aliens/dms/domain/auth/exception/.gitkeep
  dms-domain/src/main/kotlin/team/aliens/dms/domain/auth/model/AuthCode.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/auth/model/AuthCodeLimit.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/auth/model/EmailType.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/auth/model/RefreshToken.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/auth/service/.gitkeep
  dms-domain/src/main/kotlin/team/aliens/dms/domain/auth/spi/.gitkeep
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/auth/mapper/AuthCodeLimitMapper.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/auth/mapper/AuthCodeMapper.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/auth/mapper/RefreshTokenMapper.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/auth/model/AuthCodeEntity.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/auth/model/AuthCodeLimitEntity.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/auth/model/RefreshTokenEntity.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/auth/repository/AuthCodeEntityRepository.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/auth/repository/AuthCodeLimitRepository.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/auth/repository/RefreshTokenRepository.kt
Labels: setting

#15 merge: (#13) annotation setting
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/DependencyVersions.kt
  dms-application/build.gradle.kts
  dms-application/src/main/kotlin/team/aliens/dms/global/annotation/.gitkeep
  dms-application/src/main/kotlin/team/aliens/dms/global/annotation/ReadOnlyUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/global/annotation/UseCase.kt
  dms-domain/src/main/kotlin/team/aliens/dms/global/annotation/DomainService.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/aop/GlobalComponentScan.kt
Labels: setting

#16 merge: (#9) JWT Token 세팅
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/DependencyVersions.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/auth/dto/response/TokenResponse.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/auth/spi/JwtPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/user/spi/.gitkeep
  dms-application/src/main/kotlin/team/aliens/dms/domain/user/spi/UserJwtPort.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/auth/model/Authority.kt
  dms-infrastructure/build.gradle.kts
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/config/.gitkeep
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/config/ConfigurationPropertiesConfig.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/exception/InternalServerErrorException.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/filter/ExceptionFilter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/filter/FilterConfig.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/filter/JwtFilter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityProperties.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/error/SecurityErrorCode.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/exception/.gitkeep
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/exception/ExpiredTokenException.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/exception/InvalidRoleException.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/exception/InvalidTokenException.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/exception/UnexpectedTokenException.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/token/.gitkeep
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/token/GenerateJwtAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/token/JwtParser.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/token/JwtProperties.kt
  dms-presentation/src/main/resources/application.yml
Labels: setting

#20 merge: (#12) code coverage
  .github/workflows/CI.yml
  .github/workflows/build.yml
  build.gradle.kts
  codecov.yml
Labels: setting

#23 merge: (#21) security principle
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/error/ErrorResponse.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/error/GlobalErrorCode.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/error/GlobalErrorHandler.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/exception/InternalServerErrorException.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/filter/ExceptionFilter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/principle/ManagerDetails.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/principle/ManagerDetailsService.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/principle/StudentDetails.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/principle/StudentDetailsService.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/token/JwtParser.kt
Labels: feat

#27 merge: (#19) FindAccountId Api
  buildSrc/src/main/kotlin/PluginVersions.kt
  dms-application/build.gradle.kts
  dms-application/src/main/kotlin/team/aliens/dms/domain/auth/spi/SecurityPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/exception/AnswerNotMatchedException.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/spi/ManagerQuerySchoolPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/spi/ManagerQueryUserPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/spi/ManagerSecurityPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/usecase/FindAccountIdUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/school/spi/SchoolPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/user/spi/UserPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/global/spi/CoveredEmailPort.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/manager/FindAccountIdUseCaseTest.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/manager/error/.gitkeep
  dms-domain/src/main/kotlin/team/aliens/dms/domain/manager/error/ManagerErrorCode.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/manager/exception/.gitkeep
  dms-domain/src/main/kotlin/team/aliens/dms/domain/manager/exception/ManagerNotFoundException.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/util/StingUtil.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/school/SchoolPersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/user/UserPersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/user/repository/UserJpaRepository.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/manager/WebManagerAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/user/dto/response/FindAccountIdResponse.kt
Labels: feat

#28 merge: (#22) 이메일 중복 검사 기능
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/usecase/CheckEmailDuplicateUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/user/spi/UserPort.kt
  dms-application/src/test/kotlin/team/aliens/dms/student/usecase/CheckEmailDuplicateUseCaseTest.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/student/error/StudentErrorCode.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/student/spi/.gitkeep
  dms-domain/src/main/kotlin/team/aliens/dms/domain/student/spi/StudentQueryUserPort.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/user/error/UserErrorCode.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/user/exception/UserEmailExistsException.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/user/UserPersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/user/repository/UserJpaRepository.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/student/StudentWebAdapter.kt
Labels: feat

#32 merge: (#24) query question api
  dms-application/src/main/kotlin/team/aliens/dms/domain/school/spi/QuerySchoolPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/school/usecase/QuerySchoolQuestionUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/school/usecase/QuerySchoolQuestionUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/school/usecase/QuerySchoolsUseCaseTests.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/school/SchoolController.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/school/dto/response/SchoolQuestionResponse.kt
Labels: feat

#40 merge: (#38) 학교 인증코드 검사 API
  dms-application/src/main/kotlin/team/aliens/dms/domain/school/exception/CodeNotMatchedException.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/school/usecase/CheckSchoolCodeUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/school/usecase/CheckSchoolCodeUseCaseTest.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/school/error/SchoolErrorCode.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/school/SchoolWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/school/dto/response/SchoolIdResponse.kt
Labels: feat

#37 merge: (#34) 학생 아이디 찾기 API
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/usecase/FindManagerAccountIdUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/dto/FindStudentAccountIdRequest.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/exception/.gitkeep
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/exception/StudentInfoNotMatchedException.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/spi/QueryStudentPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/spi/StudentPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/spi/StudentQueryUserPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/usecase/FindStudentAccountIdUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/manager/FindManagerAccountIdUseCaseTest.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/student/usecase/FindStudentAccountIdUseCaseTest.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/student/error/StudentErrorCode.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/repository/StudentJpaRepository.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/user/UserPersistenceAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/manager/ManagerWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/manager/dto/request/.gitkeep
  dms-presentation/src/main/kotlin/team/aliens/dms/manager/dto/response/FindManagerAccountIdResponse.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/student/StudentWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/student/dto/request/FindStudentAccountIdWebRequest.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/student/dto/response/.gitkeep
  dms-presentation/src/main/kotlin/team/aliens/dms/student/dto/response/FindStudentAccountIdResponse.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/user/dto/response/FindAccountIdResponse.kt
Labels: feat

#44 merge: (#30) auth관련 api 3개
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/DependencyVersions.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/auth/dto/CertifyEmailCodeRequest.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/auth/dto/CertifyEmailRequest.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/auth/dto/SendEmailCodeRequest.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/auth/exception/.gitkeep
  dms-application/src/main/kotlin/team/aliens/dms/domain/auth/exception/AuthCodeMismatchException.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/auth/exception/EmailAlreadyCertifiedException.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/auth/exception/EmailMismatchException.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/auth/spi/AuthCodeLimitPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/auth/spi/AuthCodePort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/auth/spi/AuthQueryUserPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/auth/spi/CommandAuthCodeLimitPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/auth/spi/CommandAuthCodePort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/auth/spi/QueryAuthCodeLimitPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/auth/spi/QueryAuthCodePort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/auth/spi/SendEmailPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/auth/usecase/.gitkeep
  dms-application/src/main/kotlin/team/aliens/dms/domain/auth/usecase/CertifyEmailCodeUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/auth/usecase/CertifyEmailUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/auth/usecase/SendEmailCodeUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/user/spi/UserPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/global/spi/ReceiveRandomStringPort.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/auth/usecase/CertifyEmailCodeUseCaseTest.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/auth/usecase/CertifyEmailUseCaseTest.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/auth/usecase/SendEmailCodeUseCaseTest.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/manager/usecase/FindManagerAccountIdUseCaseTest.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/auth/error/.gitkeep
  dms-domain/src/main/kotlin/team/aliens/dms/domain/auth/error/AuthErrorCode.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/auth/exception/.gitkeep
  dms-domain/src/main/kotlin/team/aliens/dms/domain/auth/exception/AuthCodeNotFoundException.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/auth/exception/AuthCodeOverLimitException.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/auth/model/AuthCode.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/auth/model/AuthCodeLimit.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/auth/model/EmailType.kt
  dms-infrastructure/build.gradle.kts
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/config/ConfigurationPropertiesConfig.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/error/GlobalErrorCode.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/util/StingUtil.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/auth/AuthCodeLimitPersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/auth/AuthCodePersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/auth/repository/AuthCodeEntityRepository.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/auth/repository/AuthCodeLimitRepository.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/user/UserPersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/user/repository/UserJpaRepository.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/email/.gitkeep
  dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/email/AwsSESAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/email/AwsSESProperties.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/email/exception/SendEmailRejectedException.kt
  dms-infrastructure/src/main/resources/application.yml
  dms-presentation/src/main/kotlin/team/aliens/dms/auth/AuthWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/auth/dto/request/CertifyEmailCodeWebRequest.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/auth/dto/request/CertifyEmailWebRequest.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/auth/dto/request/EmailType.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/auth/dto/request/SendEmailCodeWebRequest.kt
Labels: feat

#42 merge: (#41) 학생 비밀번호 재설정 API
  dms-application/src/main/kotlin/team/aliens/dms/domain/auth/spi/AuthCodePort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/auth/spi/SecurityPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/dto/ResetStudentPasswordRequest.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/spi/StudentCommandUserPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/spi/StudentQueryAuthCodePort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/spi/StudentQueryUserPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/spi/StudentSecurityPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/usecase/ResetStudentPasswordUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/user/spi/UserPort.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/student/usecase/ResetStudentPasswordUseCaseTest.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/auth/error/AuthErrorCode.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/auth/exception/AuthCodeNotMatchedException.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/auth/AuthCodePersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/auth/model/AuthCodeEntity.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/auth/repository/AuthCodeEntityRepository.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/user/UserPersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/user/repository/UserJpaRepository.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/student/StudentWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/student/dto/request/.gitkeep
  dms-presentation/src/main/kotlin/team/aliens/dms/student/dto/request/ResetStudentPasswordWebRequest.kt
Labels: feat

#56 merge: (#53) send email code api
  dms-application/src/main/kotlin/team/aliens/dms/domain/auth/spi/QueryAuthCodeLimitPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/auth/spi/QueryAuthCodePort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/auth/usecase/CertifyEmailCodeUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/auth/usecase/SendEmailCodeUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/spi/StudentQueryAuthCodePort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/usecase/ResetStudentPasswordUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/auth/usecase/CertifyEmailCodeUseCaseTest.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/auth/usecase/SendEmailCodeUseCaseTest.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/student/usecase/ResetStudentPasswordUseCaseTest.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/auth/model/AuthCode.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/auth/model/AuthCodeLimit.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/auth/AuthCodeLimitPersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/auth/AuthCodePersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/auth/mapper/AuthCodeLimitMapper.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/auth/mapper/AuthCodeMapper.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/auth/model/AuthCodeEntity.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/auth/model/AuthCodeLimitEntity.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/auth/repository/AuthCodeEntityRepository.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/auth/repository/AuthCodeLimitRepository.kt
Labels: feat, refactor

#52 merge: (#51) check school code api 수정
  dms-application/src/main/kotlin/team/aliens/dms/domain/school/spi/QuerySchoolPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/school/usecase/CheckSchoolCodeUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/school/usecase/CheckSchoolCodeUseCaseTest.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/school/SchoolPersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/school/repository/SchoolJpaRepository.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/school/SchoolWebAdapter.kt
Labels: refactor

#50 merge: (#48) 아이디 존재 여부 확인 API
  dms-application/src/main/kotlin/team/aliens/dms/domain/auth/usecase/CheckAccountIdExistenceUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/auth/usecase/CheckAccountIdExistenceUseCaseTest.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/auth/AuthWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/auth/dto/response/CheckAccountIdExistenceResponse.kt
Labels: feat

#46 merge: (#18) signup
  dms-application/src/main/kotlin/team/aliens/dms/domain/auth/dto/TokenResponse.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/auth/spi/JwtPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/school/spi/SchoolPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/dto/SignupRequest.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/dto/TokenAndFeaturesResponse.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/spi/CommandStudentPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/spi/StudentJwtPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/spi/StudentPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/spi/StudentQuerySchoolPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/usecase/SignupUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/user/spi/UserPort.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/student/usecase/SignUpUseCaseTests.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/user/model/User.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/token/GenerateJwtAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/user/UserPersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/user/mapper/UserMapper.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/.gitkeep
  dms-presentation/src/main/kotlin/team/aliens/dms/RegexUtil.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/student/StudentWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/student/dto/request/SignupWebRequest.kt
Labels: feat

#47 merge: (#43) 관리자 비밀번호 재설정 API
  dms-application/src/main/kotlin/team/aliens/dms/domain/auth/exception/AuthCodeNotMatchedException.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/auth/spi/AuthCodePort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/dto/ResetManagerPasswordRequest.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/exception/.gitkeep
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/exception/ManagerInfoNotMatchedException.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/spi/ManagerCommandUserPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/spi/ManagerQueryAuthCodePort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/spi/ManagerQueryUserPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/spi/ManagerSecurityPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/usecase/ResetManagerPasswordUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/user/spi/UserPort.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/manager/usecase/ResetManagerPasswordUseCaseTest.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/manager/error/ManagerErrorCode.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/manager/ManagerWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/manager/dto/request/.gitkeep
  dms-presentation/src/main/kotlin/team/aliens/dms/manager/dto/request/ResetPasswordManagerWebRequest.kt
Labels: feat

#60 merge: (#58) get notice status api
  dms-application/src/main/kotlin/team/aliens/dms/domain/notice/dto/.gitkeep
  dms-application/src/main/kotlin/team/aliens/dms/domain/notice/exception/.gitkeep
  dms-application/src/main/kotlin/team/aliens/dms/domain/notice/spi/NoticePort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/notice/spi/QueryNoticePort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/notice/usecase/QueryNoticeStatusUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/notice/usecase/QueryNoticeStatusUseCaseTests.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/notice/error/.gitkeep
  dms-domain/src/main/kotlin/team/aliens/dms/domain/notice/exception/.gitkeep
  dms-domain/src/main/kotlin/team/aliens/dms/domain/notice/model/Notice.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/notice/service/.gitkeep
  dms-domain/src/main/kotlin/team/aliens/dms/domain/notice/spi/.gitkeep
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/notice/NoticePersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/notice/entity/NoticeJpaEntity.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/notice/mapper/NoticeMapper.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/notice/repository/NoticeJpaRepository.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/notice/NoticeWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/notice/dto/request/.gitkeep
  dms-presentation/src/main/kotlin/team/aliens/dms/notice/dto/response/GetNoticeStatusResponse.kt
Labels: feat

#55 merge: (#54) 토큰 재발급 api
  dms-application/src/main/kotlin/team/aliens/dms/domain/auth/dto/ReissueTokenResponse.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/auth/spi/JwtPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/auth/spi/QueryRefreshTokenPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/auth/spi/RefreshTokenPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/auth/usecase/ReissueTokenUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/spi/StudentJwtPort.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/auth/usecase/ReissueTokenUseCaseTest.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/auth/error/AuthErrorCode.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/auth/exception/RefreshTokenNotFoundException.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/auth/model/RefreshToken.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/token/GenerateJwtAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/util/StingUtil.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/auth/RefreshTokenPersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/auth/mapper/RefreshTokenMapper.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/auth/model/RefreshTokenEntity.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/auth/repository/RefreshTokenRepository.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/auth/AuthWebAdapter.kt
Labels: feat

#62 merge: (#61) 급식 조회 API
  dms-application/src/main/kotlin/team/aliens/dms/domain/auth/spi/SecurityPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/meal/dto/QueryMealsResponse.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/meal/spi/MealPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/meal/spi/MealQueryStudentPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/meal/spi/MealSecurityPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/meal/spi/QueryMealPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/meal/usecase/QueryMealsUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/spi/StudentPort.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/meal/usecase/QueryMealsUseCaseTest.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/meal/error/.gitkeep
  dms-domain/src/main/kotlin/team/aliens/dms/domain/meal/error/MealErrorCode.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/meal/exception/.gitkeep
  dms-domain/src/main/kotlin/team/aliens/dms/domain/meal/exception/MealNotFoundException.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/meal/model/Meal.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/meal/MealPersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/meal/repository/MealJpaRepository.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/meal/MealWebAdapter.kt
Labels: feat

#66 merge: (#57) signup test
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/usecase/SignUpUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/student/usecase/SignUpUseCaseTests.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/student/StudentWebAdapter.kt
Labels: test

#68 merge: (#67) aws autoconfigure dependency 추가
  buildSrc/src/main/kotlin/Dependencies.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/config/AwsProperties.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/config/ConfigurationPropertiesConfig.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/email/AwsSesConfig.kt
  dms-infrastructure/src/main/resources/application.yml
Labels: setting
