Repository team-aliens/DMS-Backend, pull requests merged in 2023-04, with the labels that each got.

#410 chore: excel 값 없는 row 예외처리
  dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/parser/ExcelAdapter.kt
Labels: 👾bug

#412 merge: (#411) 학생 tag filter 조건문 변경
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
Labels: feat

#417 merge: (#416) 공지 상세 id 조회
  dms-application/src/main/kotlin/team/aliens/dms/domain/notice/dto/QueryNoticeDetailsResponse.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/notice/usecase/QueryNoticeDetailsUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/notice/usecase/QueryNoticeDetailsUseCaseTests.kt
Labels: feat

#415 merge: (#414) 자습실에 해당하는 seatType 조회
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/QuerySeatTypePort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/QuerySeatTypesUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/studyroom/stub/StudyRoomStub.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/studyroom/usecase/QuerySeatTypesUseCaseTests.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/SeatTypePersistenceAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/StudyRoomWebAdapter.kt
Labels: feat

#428 merge: (#427) lazy로딩 문제
  dms-core/src/main/kotlin/team/aliens/dms/domain/manager/spi/QueryManagerPort.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/student/spi/QueryStudentPort.kt
  dms-core/src/test/kotlin/team/aliens/dms/domain/point/model/PointHistoryTests.kt
  dms-infrastructure/build.gradle.kts
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/principle/ManagerDetailsService.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/principle/StudentDetailsService.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/manager/ManagerPersistenceAdapter.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
Labels: 👾bug

#432 merge: (#425) logging추가
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/DependencyVersions.kt
  dms-infrastructure/build.gradle.kts
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/filter/ExceptionFilter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/principle/StudentDetailsService.kt
  dms-infrastructure/src/main/resources/application.yml
Labels: setting

#439 merge: (#438) 자습실 취소 시 모든 신청이 다 취소되는 오류
  dms-core/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/CommandStudyRoomPort.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/ApplySeatUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/UnApplySeatUseCase.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/studyroom/StudyRoomPersistenceAdapter.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/studyroom/repository/SeatApplicationJpaRepository.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/StudyRoomWebAdapter.kt
Labels: 👾bug

#435 merge: (#433) 에러코드 추가
  dms-core/src/main/kotlin/team/aliens/dms/common/error/ErrorProperty.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/auth/exception/error/AuthErrorCode.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/file/exception/error/FileErrorCode.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/manager/exception/error/ManagerErrorCode.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/notice/exception/error/NoticeErrorCode.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/point/exception/error/PointHistoryErrorCode.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/point/exception/error/PointOptionErrorCode.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/remain/exception/error/RemainAvailableTimeErrorCode.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/remain/exception/error/RemainOptionErrorCode.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/remain/exception/error/RemainStatusErrorCode.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/room/exception/error/RoomErrorCode.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/school/exception/error/SchoolErrorCode.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/student/exception/error/StudentErrorCode.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/student/exception/error/VerifiedStudentErrorCode.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/studyroom/exception/error/AvailableTimeErrorCode.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/studyroom/exception/error/SeatErrorCode.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/studyroom/exception/error/SeatTypeErrorCode.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/studyroom/exception/error/StudyRoomErrorCode.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/tag/exception/error/TagErrorCode.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/user/exception/error/UserErrorCode.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/error/ErrorResponse.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/error/GlobalErrorCode.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/exception/error/SecurityErrorCode.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/api/error/OtherServerErrorCode.kt
Labels: feat

#437 chore: (#436) studyroom excel 신청 여러개인 경우 출력 오류
  dms-core/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/vo/StudentSeatInfo.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/ExportStudyRoomApplicationStatusUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/StudentQueryStudyRoomsUseCase.kt
  dms-core/src/test/kotlin/team/aliens/dms/domain/studyroom/usecase/ExportStudyRoomStudentsApplicationStatusUseCaseTests.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/parser/ExcelAdapter.kt
  dms-infrastructure/src/test/kotlin/team/aliens/dms/thirdparty/parser/ExcelAdapterTests.kt
Labels: 👾bug

#448 merge: (#446) meal facade분리
  dms-core/src/main/kotlin/team/aliens/dms/common/service/feign/FeignService.kt
  dms-core/src/main/kotlin/team/aliens/dms/common/service/feign/NeisFeignService.kt
  dms-core/src/main/kotlin/team/aliens/dms/common/service/feign/NeisFeignServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/common/service/security/SecurityService.kt
  dms-core/src/main/kotlin/team/aliens/dms/common/service/security/SecurityServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/auth/usecase/SignInUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/manager/usecase/ResetManagerPasswordUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/meal/service/CommandMealService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/meal/service/CommandMealServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/meal/service/GetMealService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/meal/service/GetMealServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/meal/service/MealService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/meal/usecase/QueryMealsUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/meal/usecase/SaveAllMealsUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/school/service/GetSchoolService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/school/service/GetSchoolServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/school/service/SchoolService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/student/usecase/ResetStudentPasswordUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/student/usecase/SignUpUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/student/usecase/StudentWithdrawalUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/UnApplySeatUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/user/service/CheckUserService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/user/service/CommandUserServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/user/service/GetUserService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/user/service/GetUserServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/user/usecase/UpdateUserPasswordUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/user/usecase/UserPasswordCompareUseCase.kt
Labels: feat

#451 merge: (#450) 탈퇴시 유저만 삭제
  dms-core/src/main/kotlin/team/aliens/dms/domain/student/usecase/SignUpUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/student/usecase/StudentWithdrawalUseCase.kt
Labels: feat

#456 merge: (#455) Point Facade 분리
  dms-core/src/main/kotlin/team/aliens/dms/domain/manager/usecase/QueryStudentDetailsUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/point/model/PointHistory.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/point/model/PointOption.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/point/service/CheckPointService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/point/service/CheckPointServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/point/service/CommandPointService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/point/service/CommandPointServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/point/service/GetPointService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/point/service/GetPointServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/point/service/PointService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/point/usecase/CancelGrantedPointUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/point/usecase/CreatePointOptionUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/point/usecase/ExportAllPointHistoryUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/point/usecase/GrantPointUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/point/usecase/QueryAllPointHistoryUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/point/usecase/QueryPointHistoryUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/point/usecase/QueryPointOptionsUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/point/usecase/QueryStudentPointHistoryUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/point/usecase/RemovePointOptionUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/point/usecase/UpdatePointOptionUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/student/usecase/StudentMyPageUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/student/usecase/StudentWithdrawalUseCase.kt
Labels: feat

#458 merge: (#457) 엑셀 동적 에러메시지 구현
  dms-core/src/main/kotlin/team/aliens/dms/common/error/DynamicDmsException.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/file/exception/BadExcelFormatException.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/error/GlobalErrorCode.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/parser/ExcelAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/parser/exception/BadExcelFormatException.kt
Labels: feat

#462 merge: (#459) notice facade분리
  dms-core/src/main/kotlin/team/aliens/dms/domain/notice/service/CheckNoticeService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/notice/service/CheckNoticeServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/notice/service/CommandNoticeService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/notice/service/CommandNoticeServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/notice/service/GetNoticeService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/notice/service/GetNoticeServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/notice/service/NoticeService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/notice/usecase/CreateNoticeUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/notice/usecase/QueryAllNoticesUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/notice/usecase/QueryNoticeDetailsUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/notice/usecase/QueryNoticeStatusUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/notice/usecase/RemoveNoticeUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/notice/usecase/UpdateNoticeUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/user/service/CheckUserService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/user/service/CommandUserService.kt
Labels: refactor

#453 merge: (#449) auth facade
  dms-core/src/main/kotlin/team/aliens/dms/domain/auth/model/AuthCodeLimit.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/auth/service/AuthService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/auth/service/CheckAuthCodeService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/auth/service/CommandAuthCodeService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/auth/service/GetAuthCodeService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/auth/service/impl/CheckAuthCodeServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/auth/service/impl/CommandAuthCodeServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/auth/service/impl/GetAuthCodeServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/auth/usecase/CertifyEmailCodeUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/auth/usecase/ReissueTokenUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/auth/usecase/SendEmailCodeUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/auth/usecase/SignInUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/manager/usecase/ResetManagerPasswordUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/school/service/GetSchoolService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/school/service/GetSchoolServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/student/usecase/ResetStudentPasswordUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/student/usecase/SignUpUseCase.kt
Labels: refactor

#467 merge: (#466) room Facade 분리
  dms-core/src/main/kotlin/team/aliens/dms/domain/file/usecase/ImportStudentUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/room/service/CommandRoomService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/room/service/CommandRoomServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/room/service/RoomService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/room/spi/CommandRoomPort.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/room/spi/QueryRoomPort.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/room/spi/RoomPort.kt
Labels: refactor

#470 merge: (#469) File Facade 분리
  dms-core/src/main/kotlin/team/aliens/dms/common/error/DynamicDmsException.kt
  dms-core/src/main/kotlin/team/aliens/dms/common/service/security/SecurityService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/auth/model/AuthCodeLimit.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/auth/service/GetAuthCodeService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/auth/service/impl/CheckAuthCodeServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/file/service/FileService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/file/service/ParseFileService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/file/service/ParseFileServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/file/service/WriteFileService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/file/service/WriteFileServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/file/usecase/ImportStudentUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/manager/usecase/ResetManagerPasswordUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/point/usecase/ExportAllPointHistoryUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/point/usecase/QueryStudentPointHistoryUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/remain/usecase/ExportRemainStatusUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/room/service/CommandRoomServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/school/service/GetSchoolService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/school/service/GetSchoolServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/student/model/Student.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/student/usecase/ResetStudentPasswordUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/ExportStudyRoomApplicationStatusUseCase.kt
Labels: refactor

#471 merge: (#468) School Facade 분리
  dms-core/src/main/kotlin/team/aliens/dms/domain/manager/usecase/FindManagerAccountIdUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/manager/usecase/ManagerMyPageUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/meal/usecase/SaveAllMealsUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/point/usecase/ExportAllPointHistoryUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/remain/usecase/ExportRemainStatusUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/school/aop/AvailableFeatureAspect.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/school/model/School.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/school/service/CommandSchoolService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/school/service/CommandSchoolServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/school/service/GetSchoolService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/school/service/GetSchoolServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/school/service/SchoolService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/school/usecase/CheckSchoolAnswerUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/school/usecase/CheckSchoolCodeUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/school/usecase/QueryAvailableFeaturesUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/school/usecase/QuerySchoolQuestionUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/school/usecase/QuerySchoolsUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/school/usecase/ReissueSchoolCodeUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/school/usecase/UpdateQuestionUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/student/usecase/CheckStudentGcnUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/student/usecase/SignUpUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/student/usecase/StudentMyPageUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/ExportStudyRoomApplicationStatusUseCase.kt
Labels: refactor

#465 merge: (#464) Remain Facade 분리
  dms-core/src/main/kotlin/team/aliens/dms/domain/manager/usecase/FindManagerAccountIdUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/manager/usecase/RemoveStudentUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/remain/model/RemainAvailableTime.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/remain/service/CommandRemainService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/remain/service/CommandRemainServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/remain/service/GetRemainService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/remain/service/GetRemainServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/remain/service/RemainService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/remain/usecase/ApplyRemainUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/remain/usecase/ExportRemainStatusUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/remain/usecase/QueryCurrentAppliedRemainOptionUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/remain/usecase/QueryRemainAvailableTimeUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/remain/usecase/QueryRemainOptionsUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/remain/usecase/RemoveRemainOptionUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/remain/usecase/UpdateRemainAvailableTimeUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/remain/usecase/UpdateRemainOptionUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/school/usecase/CheckSchoolAnswerUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/student/usecase/SignUpUseCase.kt
Labels: refactor

#480 merge: config로 명칭 통일
  dms-core/src/main/kotlin/team/aliens/dms/domain/manager/usecase/UpdateStudentGcnByFileUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/student/service/GetStudentService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/student/service/GetStudentServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/student/usecase/SignUpUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/ExportStudyRoomApplicationStatusUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/UnApplySeatUseCase.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/config/ComponentScanConfig.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/config/JacksonConfig.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/config/PropertiesScanConfig.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfig.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/scheduler/config/EnableSchedulingConfig.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/api/config/EnableFeignClientsConfig.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/manager/ManagerWebAdapter.kt
Labels: refactor
