Repository team-aliens/DMS-Backend, pull requests merged in 2023-03, with the labels that each got.

#294 merge: (#221) Cron 서버 이전
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/DependencyVersions.kt
  dms-application/src/main/kotlin/team/aliens/dms/common/spi/NeisFeignClientPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/meal/dto/NeisMealServiceDietInfosResponse.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/meal/spi/CommandMealPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/meal/spi/MealFeignClientPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/meal/spi/MealFeignClientSchoolPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/meal/spi/MealPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/meal/spi/MealQuerySchoolPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/meal/usecase/SaveAllMealsUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/school/dto/NeisSchoolResponse.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/school/spi/SchoolPort.kt
  dms-infrastructure/build.gradle.kts
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/meal/MealPersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/scheduler/MealScheduler.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/scheduler/config/EnableSchedulingConfiguration.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/api/NeisFeignClientAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/api/client/NeisFeignClient.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/api/client/dto/NeisFeignClientMealServiceDietInfoResponse.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/api/client/dto/NeisFeignClientSchoolInfoResponse.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/api/client/property/NeisFeignClientProperty.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/api/config/EnableFeignClientsConfiguration.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/api/error/FeignClientErrorDecoder.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/api/error/OtherServerErrorCode.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/api/exception/OtherServerBadRequestException.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/api/exception/OtherServerForbiddenException.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/api/exception/OtherServerUnauthorizedException.kt
  dms-infrastructure/src/main/resources/application.yml
Labels: feat

#304 merge: (#302) 자습실 자리 초기화
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/CommandStudyRoomPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/QueryStudyRoomPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/ResetAllStudyRoomsUseCase.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/StudyRoomPersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/repository/SeatJpaRepository.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/scheduler/StudyRoomScheduler.kt
Labels: feat

#301 merge: (#300) 삭제된 student 조회 막기
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/usecase/RemoveStudentUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/usecase/StudentWithdrawalUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/manager/usecase/RemoveStudentUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/student/usecase/StudentWithdrawalUseCaseTests.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/student/model/Student.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/entity/StudentJpaEntity.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/mapper/StudentMapper.kt
Labels: feat

#309 merge: (#305) 잔류 신청 시간 설정 접근 권한 오류
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
Labels: 👾bug

#310 merge: pointFilter 오류 수정
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
Labels: 👾bug

#311 merge: 급식 조회 오류 해결
  dms-application/src/main/kotlin/team/aliens/dms/domain/meal/dto/QueryMealsResponse.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/meal/usecase/QueryMealsUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/usecase/GrantPointUseCase.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/meal/model/Meal.kt
Labels: 👾bug, refactor

#313 bug: cancel시 최근 total 기준으로 계산
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/usecase/CancelGrantedPointUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/point.usecase/CancelGrantedPointUseCaseTests.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/point/model/PointHistory.kt
  dms-domain/src/test/kotlin/team/aliens/dms/point/model/PointHistoryTests.kt
Labels: 👾bug

#315 feat: 학번 존재 체크
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/spi/QueryStudentPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/usecase/SignUpUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/student/usecase/SignUpUseCaseTests.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/repository/StudentJpaRepository.kt
Labels: feat

#308 merge: (#271) domain module detekt
  .github/workflows/build.yml
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/usecase/SignUpUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/CommandStudyRoomPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/QueryStudyRoomPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/ResetAllStudyRoomsUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/student/usecase/SignUpUseCaseTests.kt
  dms-domain/src/main/kotlin/team/aliens/dms/common/annotation/Aggregate.kt
  dms-domain/src/main/kotlin/team/aliens/dms/common/annotation/DomainService.kt
  dms-domain/src/main/kotlin/team/aliens/dms/common/error/ErrorStatus.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/auth/error/AuthErrorCode.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/file/error/FileErrorCode.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/file/model/File.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/manager/error/ManagerErrorCode.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/notice/error/NoticeErrorCode.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/point/error/PointHistoryErrorCode.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/point/error/PointOptionErrorCode.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/remain/error/RemainAvailableTimeErrorCode.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/remain/error/RemainOptionErrorCode.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/remain/error/RemainStatusErrorCode.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/room/error/RoomErrorCode.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/school/error/SchoolErrorCode.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/student/error/StudentErrorCode.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/student/error/VerifiedStudentErrorCode.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/student/model/Student.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/studyroom/error/AvailableTimeErrorCode.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/studyroom/error/SeatErrorCode.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/studyroom/error/SeatTypeErrorCode.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/studyroom/error/StudyRoomErrorCode.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/user/error/UserErrorCode.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/StudyRoomPersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/repository/SeatJpaRepository.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/scheduler/StudyRoomScheduler.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/common/WebMvcConfig.kt
Labels: refactor

#325 bug: (#324) 상벌점 내역 출력 시 취소 내역 제외
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/point/PointHistoryPersistenceAdapter.kt
Labels: 👾bug

#328 merge: (#327) 사용가능 기능 조회api
  dms-application/src/main/kotlin/team/aliens/dms/domain/school/dto/QueryAvailableFeaturesResponse.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/school/usecase/QueryAvailableFeaturesUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/school/usecase/QueryAvailableFeaturesUseCaseTest.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/school/SchoolWebAdapter.kt
Labels: feat

#321 merge: (#317) 학생 중복 검사
  dms-application/src/main/kotlin/team/aliens/dms/domain/file/usecase/ImportVerifiedStudentUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/spi/QueryStudentPort.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/point.usecase/CancelGrantedPointUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/student/usecase/SignUpUseCaseTests.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/student/model/VerifiedStudent.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
Labels: refactor

#322 merge: 자습실 신청 Exception 처리
  dms-application/src/main/kotlin/team/aliens/dms/domain/notice/spi/QueryNoticePort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/notice/usecase/QueryNoticeStatusUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/ApplySeatUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/notice/usecase/QueryNoticeStatusUseCaseTests.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/studyroom/exception/SeatCanNotAppliedException.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/studyroom/model/Seat.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/notice/NoticePersistenceAdapter.kt
Labels: 👾bug

#330 merge: (#329) 인증코드 검사 삭제
  dms-application/src/main/kotlin/team/aliens/dms/domain/auth/exception/UnverifiedAuthCodeException.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/auth/spi/AuthCodeLimitPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/spi/StudentQueryAuthCodeLimitPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/usecase/SignUpUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/student/usecase/SignUpUseCaseTests.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/auth/error/AuthErrorCode.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/auth/AuthCodeLimitPersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/auth/repository/AuthCodeLimitRepository.kt
Labels: refactor

#333 merge: (#303) Prod Dev 환경분리
  .github/workflows/dev-cd.yml
  .github/workflows/prod-cd.yml
Labels: setting

#337 merge: (#334) 자습실 이용시간 Entity setting + DB 구조 수정
  dms-application/src/main/kotlin/team/aliens/dms/domain/auth/exception/UnverifiedAuthCodeException.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/school/usecase/QueryAvailableFeaturesUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/spi/StudentQueryAuthCodeLimitPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/CreateStudyRoomUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/school/usecase/QueryAvailableFeaturesUseCaseTest.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/studyroom/model/SeatApplication.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/studyroom/model/StudyRoomInfo.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/studyroom/model/StudyRoomTimeSlot.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/entity/SeatApplicationJpaEntity.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/entity/SeatJpaEntity.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/entity/StudyRoomInfoJpaEntity.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/entity/StudyRoomTimeSlotJpaEntity.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/mapper/SeatApplicationMapper.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/mapper/SeatMapper.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/mapper/StudyRoomInfoMapper.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/mapper/StudyRoomTimeSlotMapper.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/repository/SeatApplicationJpaRepository.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/repository/SeatJpaRepository.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/repository/StudyRoomInfoJpaRepository.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/repository/StudyRoomTimeSlotJpaRepository.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/school/SchoolWebAdapter.kt
Labels: setting

#341 merge: (#340) CI Trigger수정
  .github/workflows/CI.yml
  .github/workflows/build.yml
Labels: setting

#343 merge: localDateTime response format config
  buildSrc/src/main/kotlin/Dependencies.kt
  dms-infrastructure/build.gradle.kts
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/config/JacksonConfiguration.kt
Labels: feat

#338 merge: (#336) schedulerUseCase aop제외
  dms-application/build.gradle.kts
  dms-application/src/main/kotlin/team/aliens/dms/common/annotation/SchedulerUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/auth/exception/UnverifiedAuthCodeException.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/meal/usecase/SaveAllMealsUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/school/aop/AvailableFeatureAspect.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/school/usecase/QueryAvailableFeaturesUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/spi/StudentQueryAuthCodeLimitPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/ResetAllStudyRoomsUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/school/usecase/QueryAvailableFeaturesUseCaseTest.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/config/ComponentScanConfiguration.kt
Labels: 👾bug

#344 merge: (#339) 상벌점 필터 엔티티 세팅
  dms-domain/src/main/kotlin/team/aliens/dms/domain/point/model/PointFilter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/point/entity/PointFilterJpaEntity.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/point/mapper/PointFilterMapper.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/point/repository/PointFilterJpaRepository.kt
Labels: setting

#348 merge: (#347) DevCD Trigger변경
  .github/workflows/dev-cd.yml
Labels: setting

#350 bug: snake case
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/config/JacksonConfiguration.kt
  dms-infrastructure/src/main/resources/application.yml
Labels: 👾bug

#354 merge: (#353) trigger to tag
  .github/workflows/prod-cd.yml
Labels: setting

#352 merge: (#351) timeSlot, studyRoomTimeSlot 엔티티 정의 및 일부 UseCase 반영
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/spi/ManagerCommandStudyRoomPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/spi/StudentCommandStudyRoomPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/StudyRoomFacade.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/CreateStudyRoomRequest.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/UpdateStudyRoomRequest.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/exception/TimeSlotNotFoundException.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/CommandStudyRoomPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/QueryStudyRoomPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/StudyRoomPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/ApplySeatUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/CreateStudyRoomUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/ManagerQueryStudyRoomUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/ManagerQueryStudyRoomsUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/RemoveStudyRoomUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/StudentQueryStudyRoomUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/StudentQueryStudyRoomsUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/UnApplySeatUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/UpdateStudyRoomUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/manager/usecase/RemoveStudentUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/student/usecase/StudentWithdrawalUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/studyroom/StudyRoomFacadeTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/studyroom/usecase/ApplySeatUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/studyroom/usecase/CreateStudyRoomUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/studyroom/usecase/ManagerQueryStudyRoomUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/studyroom/usecase/ManagerQueryStudyRoomsUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/studyroom/usecase/StudentQueryStudyRoomUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/studyroom/usecase/StudentQueryStudyRoomsUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/studyroom/usecase/UpdateStudyRoomUseCaseTests.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/studyroom/error/StudyRoomErrorCode.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/studyroom/model/StudyRoomTimeSlot.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/studyroom/model/TimeSlot.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/StudyRoomPersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/entity/SeatApplicationJpaEntity.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/entity/StudyRoomTimeSlotJpaEntity.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/entity/TimeSlotJpaEntity.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/mapper/SeatApplicationMapper.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/mapper/StudyRoomTimeSlotMapper.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/mapper/TimeSlotMapper.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/repository/SeatApplicationJpaRepository.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/repository/StudyRoomTimeSlotJpaRepository.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/repository/TimeSlotJpaRepository.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/common/validator/NotNullElementsValidator.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/point/dto/request/GrantPointWebRequest.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/StudyRoomWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/CreateStudyRoomWebRequest.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/UpdateStudyRoomWebRequest.kt
Labels: feat

#357 merge: (#355) 이용시간 생성, 수정 api
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/exception/TimeSlotAlreadyExistsException.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/QueryStudyRoomPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/CreateTimeSlotUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/UpdateTimeSlotUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/studyroom/usecase/CreateTimeSlotUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/studyroom/usecase/UpdateTimeSlotUseCaseTests.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/studyroom/error/StudyRoomErrorCode.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/StudyRoomPersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/repository/TimeSlotJpaRepository.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/StudyRoomWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/CreateTimeSlotWebRequest.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/CreateTimeSlotWebResponse.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/UpdateTimeSlotWebRequest.kt
Labels: feat

#362 merge: (#360) 이용시간 조회 api + 자습실 상세 조회시 이용시간 정보 반환
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/ManagerQueryStudyRoomResponse.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/QueryTimeSlotsResponse.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/StudentQueryStudyRoomResponse.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/QueryStudyRoomPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/ManagerQueryStudyRoomUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/QueryTimeSlotsUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/StudentQueryStudyRoomUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/studyroom/usecase/ManagerQueryStudyRoomUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/studyroom/usecase/StudentQueryStudyRoomUseCaseTests.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/config/JacksonConfiguration.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/StudyRoomPersistenceAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/StudyRoomWebAdapter.kt
Labels: feat

#370 merge: (#369) 패키지 분리
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/ManagerQueryStudyRoomResponse.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/StudentQueryStudyRoomResponse.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/exception/TimeSlotAlreadyExistsException.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/QueryStudyRoomPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/CreateTimeSlotUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/ManagerQueryStudyRoomUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/StudentQueryStudyRoomUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/UpdateTimeSlotUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/tag/dto/.gitkeep
  dms-application/src/main/kotlin/team/aliens/dms/domain/tag/exception/.gitkeep
  dms-application/src/main/kotlin/team/aliens/dms/domain/tag/spi/TagPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/tag/usecase/.gitkeep
  dms-application/src/test/kotlin/team/aliens/dms/domain/manager/usecase/RemoveStudentUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/student/usecase/StudentWithdrawalUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/studyroom/usecase/CreateTimeSlotUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/studyroom/usecase/ManagerQueryStudyRoomUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/studyroom/usecase/StudentQueryStudyRoomUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/studyroom/usecase/UpdateStudyRoomUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/studyroom/usecase/UpdateTimeSlotUseCaseTests.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/tag/error/TagErrorCode.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/tag/exception/.gitkeep
  dms-domain/src/main/kotlin/team/aliens/dms/domain/tag/model/StudentTag.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/tag/model/Tag.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/tag/service/.gitkeep
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/repository/StudentTagJpaRepository.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/StudyRoomPersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/repository/TimeSlotJpaRepository.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/tag/TagPersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/tag/entity/StudentTagJpaEntity.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/tag/entity/TagJpaEntity.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/tag/mapper/StudentTagMapper.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/tag/mapper/TagMapper.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/tag/repository/StudentTagJpaRepository.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/tag/repository/TagJpaRepository.kt
  dms-infrastructure/src/main/resources/application.yml
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/StudyRoomWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/CreateStudyRoomWebRequest.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/UpdateStudyRoomWebRequest.kt
Labels: setting

#368 chore: student 자습실 조회 api 명세 수정
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/StudentQueryStudyRoomResponse.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/exception/StudyRoomTimeSlotNotFoundException.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/ManagerQueryStudyRoomUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/StudentQueryStudyRoomUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/studyroom/usecase/ManagerQueryStudyRoomUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/studyroom/usecase/StudentQueryStudyRoomUseCaseTests.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/studyroom/error/StudyRoomErrorCode.kt
Labels: feat

#365 merge: (#364) 자습실 엑셀 출력 api
  dms-application/src/main/kotlin/team/aliens/dms/domain/file/spi/WriteFilePort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/ExportStudyRoomApplicationStatusResponse.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/QueryStudyRoomPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/StudyRoomQueryStudentPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/vo/StudentSeatApplicationVO.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/vo/StudentSeatInfo.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/ExportStudyRoomApplicationStatusUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/studyroom/usecase/ExportStudyRoomStudentsApplicationStatusUseCaseTests.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/student/error/StudentErrorCode.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/student/exception/.gitkeep
  dms-domain/src/main/kotlin/team/aliens/dms/domain/student/exception/SexMismatchException.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/student/model/Sex.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/studyroom/model/Seat.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/studyroom/model/StudyRoom.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/studyroom/model/TimeSlot.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/error/GlobalErrorCode.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/StudyRoomPersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/repository/vo/StudentSeatApplicationVO.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/parser/ExcelAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/parser/exception/ExcelSexMismatchException.kt
  dms-infrastructure/src/test/kotlin/team/aliens/dms/thirdparty/parser/ExcelAdapterTests.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/common/util/FileUtil.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/file/FileWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/point/PointWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/remain/RemainWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/StudyRoomWebAdapter.kt
Labels: feat

#377 merge: (#367) 학생 태그 부여 API
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/spi/StudentPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/tag/dto/GrantTagRequest.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/tag/exception/TagNotFoundException.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/tag/spi/CommandTagPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/tag/spi/QueryTagPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/tag/spi/TagQueryStudentPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/tag/usecase/GrantTagUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/tag/stub/StudentTagStub.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/tag/stub/TagStub.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/tag/usecase/GrantTagUseCaseTests.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/tag/model/StudentTag.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/repository/StudentJpaRepository.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/tag/TagPersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/tag/mapper/StudentTagMapper.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/StudyRoomWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/tag/TagWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/tag/dto/GrantTagWebRequest.kt
Labels: feat

#384 merge: (#378) 학생 태그 부여 취소 API
  dms-application/src/main/kotlin/team/aliens/dms/domain/tag/exception/TagNotFoundException.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/tag/spi/CommandTagPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/tag/spi/TagQueryStudentPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/tag/usecase/CancelGrantedTagUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/tag/usecase/CancelGrantedTagUseCaseTests.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/tag/TagPersistenceAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/tag/TagWebAdapter.kt
Labels: feat

#383 merge: (#376) remove tag
  dms-application/src/main/kotlin/team/aliens/dms/domain/tag/spi/CommandTagPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/tag/usecase/RemoveTagUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/tag/usecase/RemoveTagUseCaseTest.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/tag/TagPersistenceAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/common/util/FileUtil.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/point/PointWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/remain/RemainWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/tag/TagWebAdapter.kt
Labels: feat

#380 merge: (#379) studyroom 엑셀 출력 seat 이름 형식
  dms-application/src/main/kotlin/team/aliens/dms/domain/file/spi/WriteFilePort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/QueryStudyRoomPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/vo/StudentSeatApplicationVO.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/ExportStudyRoomApplicationStatusUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/studyroom/usecase/ExportStudyRoomStudentsApplicationStatusUseCaseTests.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/studyroom/model/Seat.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/studyroom/model/StudyRoom.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/StudyRoomPersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/repository/vo/StudentSeatApplicationVO.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/parser/ExcelAdapter.kt
  dms-infrastructure/src/test/kotlin/team/aliens/dms/thirdparty/parser/ExcelAdapterTests.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/common/util/FileUtil.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/point/PointWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/remain/RemainWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/StudyRoomWebAdapter.kt
Labels: feat

#388 merge: (#386) 학생 상세 확인 API 수정
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/dto/GetStudentDetailsResponse.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/spi/ManagerQueryTagPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/usecase/QueryStudentDetailsUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/tag/spi/TagPort.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/manager/usecase/QueryStudentDetailsUseCaseTests.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/tag/TagPersistenceAdapter.kt
Labels: feat

#393 merge: (#392) remove tag bug
  dms-application/src/main/kotlin/team/aliens/dms/domain/tag/spi/CommandStudentTagPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/tag/spi/StudentTagPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/tag/usecase/RemoveTagUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/tag/usecase/RemoveTagUseCaseTest.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/tag/StudentTagPersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/tag/repository/StudentTagJpaRepository.kt
Labels: 👾bug

#395 merge: (#394) updateTag api
  dms-application/src/main/kotlin/team/aliens/dms/domain/tag/usecase/UpdateTagUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/tag/usecase/CreateTagUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/tag/usecase/QueryTagsUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/tag/usecase/RemoveTagUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/tag/usecase/UpdateTagUseCaseTests.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/tag/TagWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/tag/dto/UpdateTagWebRequest.kt
Labels: feat

#396 merge: 상벌점 내역 엑셀 출력 list empty 버그
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/usecase/ExportAllPointHistoryUseCase.kt
Labels: 👾bug

#400 merge: (#399) LocalDate format오류
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/config/JacksonConfiguration.kt
Labels: 👾bug

#398 merge: (#397) 태그 수정 시 중복 예외 제거
  dms-application/src/main/kotlin/team/aliens/dms/domain/tag/usecase/UpdateTagUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/tag/usecase/UpdateTagUseCaseTests.kt
Labels: 👾bug

#391 merge: (#390) tag 필터링 추가
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/spi/ManagerQueryStudentPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/usecase/QueryStudentsUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/manager/usecase/QueryStudentsUseCaseTests.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/manager/ManagerWebAdapter.kt
Labels: feat

#408 merge: (#407) 사용가능 기능 조회 학생 권한 추가
  dms-application/src/main/kotlin/team/aliens/dms/domain/school/usecase/QueryAvailableFeaturesUseCase.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
Labels: refactor

#406 merge: (#401) 태그 목록 쿼리 수정
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/spi/ManagerQueryTagPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/usecase/QueryStudentsUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/ManagerQueryStudyRoomsUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/tag/usecase/UpdateTagUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/auth/stub/AuthStub.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/manager/usecase/QueryStudentsUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/point/stub/PointStub.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/remain/stub/RemainStub.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/school/stub/SchoolStub.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/student/stub/StudentStub.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/studyroom/stub/StudyRoomStub.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/studyroom/usecase/ApplySeatUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/studyroom/usecase/CreateStudyRoomUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/studyroom/usecase/CreateTimeSlotUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/studyroom/usecase/ExportStudyRoomStudentsApplicationStatusUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/studyroom/usecase/QueryCurrentAppliedStudyRoomUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/studyroom/usecase/RemoveTimeSlotUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/studyroom/usecase/StudentQueryStudyRoomsUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/studyroom/usecase/UpdateStudyRoomUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/studyroom/usecase/UpdateTimeSlotUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/tag/usecase/RemoveTagUseCaseTests.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/studyroom/model/StudyRoom.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/tag/TagPersistenceAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/common/util/FileUtil.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/StudyRoomWebAdapter.kt
Labels: feat
