Repository team-aliens/DMS-Backend, pull requests merged in 2023-02, with the labels that each got.

#224 merge: (#222) PointHistory 비정규화
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/spi/ManagerQueryPointPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/usecase/QueryStudentDetailsUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/dto/QueryPointHistoryResponse.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/spi/PointQueryStudentPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/spi/QueryPointPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/usecase/QueryPointHistoryUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/spi/StudentPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/spi/StudentQueryPointPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/usecase/StudentMyPageUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/manager/usecase/QueryStudentDetailsUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/point.usecase/QueryPointHistoryUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/student/usecase/StudentMyPageUseCaseTests.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/point/model/PointHistory.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/point/PointPersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/point/entity/PointHistoryJpaEntity.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/point/mapper/PointHistoryMapper.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/point/repository/vo/QueryPointHistoryVO.kt
Labels: feat, refactor

#228 merge: PR TEMPLATE 수정
  .github/PULL_REQUEST_TEMPLATE.md
Labels: refactor, docs

#233 merge: (#232) PointHistoryPort 분리
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/spi/ManagerQueryPointHistoryPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/usecase/QueryStudentDetailsUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/spi/PointHistoryPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/spi/PointPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/spi/QueryPointHistoryPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/usecase/QueryPointHistoryUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/spi/StudentQueryPointHistoryPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/usecase/StudentMyPageUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/manager/usecase/QueryStudentDetailsUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/point.usecase/QueryPointHistoryUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/student/usecase/StudentMyPageUseCaseTests.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/point/PointHistoryPersistenceAdapter.kt
Labels: refactor

#238 merge: (#235) 잔류 신청 시간 엔티티 세팅
  dms-domain/src/main/kotlin/team/aliens/dms/domain/remain/model/RemainAvailableTime.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/remain/entity/RemainAvailableTimeJpaEntity.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/remain/mapper/RemainAvailableTimeMapper.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/remain/repository/RemainAvailableTimeJpaRepository.kt
Labels: setting

#231 merge: (#229) 잔류 항목 생성 api
  build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/PluginVersions.kt
  dms-application/src/main/kotlin/team/aliens/dms/common/spi/SecurityPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/remain/spi/CommandRemainOptionPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/remain/spi/RemainOptionPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/remain/spi/RemainQueryUserPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/remain/spi/RemainSecurityPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/remain/usecase/CreateRemainOptionUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/user/spi/UserPort.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/remain/usecase/CreateRemainUseCaseTests.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/remain/RemainOptionPersistenceAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/remain/RemainWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/remain/dto/request/CreateRemainOptionWebRequest.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/remain/dto/response/CreateRemainOptionResponse.kt
Labels: feat

#242 merge: (#239) 내 자습실 신청항목 보기 API
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/QueryCurrentAppliedStudyRoomResponse.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/QueryCurrentAppliedStudyRoomUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/studyroom/usecase/QueryCurrentAppliedStudyRoomUseCaseTests.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/StudyRoomWebAdapter.kt
Labels: feat

#244 merge: (#243) 잔류 항목 수정 api
  dms-application/src/main/kotlin/team/aliens/dms/domain/remain/exception/RemainOptionNotFoundException.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/remain/spi/QueryRemainOptionPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/remain/spi/RemainOptionPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/remain/usecase/UpdateRemainOptionUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/remain/usecase/UpdateRemainOptionUseCaseTests.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/remain/error/RemainOptionErrorCode.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/remain/RemainOptionPersistenceAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/remain/RemainWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/remain/dto/request/UpdateRemainOptionWebRequest.kt
Labels: feat

#241 merge: (#240) 전체 상벌점 내역 보기 api
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/DependencyVersions.kt
  dms-application/src/main/kotlin/team/aliens/dms/common/dto/PageData.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/dto/QueryAllPointHistoryResponse.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/spi/QueryPointHistoryPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/usecase/QueryAllPointHistoryUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/point.usecase/QueryAllPointHistoryUseCaseTests.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/point/PointHistoryPersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/point/repository/vo/QueryAllPointHistoryVO.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/common/dto/PageWebData.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/point/PointWebAdapter.kt
Labels: feat

#236 merge: (#230) 상벌점 부여 api
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/spi/ManagerPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/dto/GrantPointRequest.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/exception/.gitkeep
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/exception/PointOptionNotFoundException.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/spi/CommandPointHistoryPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/spi/PointHistoryPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/spi/PointOptionPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/spi/PointQueryManagerPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/spi/PointQueryStudentPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/spi/QueryPointHistoryPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/spi/QueryPointOptionPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/spi/vo/StudentWithPointVO.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/usecase/GrantPointUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/point.usecase/GrantPointUseCaseTest.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/point/error/PointOptionErrorCode.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/point/exception/.gitkeep
  dms-domain/src/main/kotlin/team/aliens/dms/domain/point/exception/PointOptionSchoolMismatchException.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/point/model/PointOption.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/point/PointHistoryPersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/point/PointOptionPersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/point/repository/PointOptionJpaRepository.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/repository/vo/QueryStudentWithPointVO.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/point/PointWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/point/dto/request/GrantPointWebRequest.kt
Labels: feat

#255 merge: (#254) 상벌점 항목 조회
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/dto/QueryPointOptionsResponse.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/spi/QueryPointOptionPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/usecase/QueryPointOptionsUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/point.usecase/QueryPointOptionsUseCaseTest.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/point/PointOptionPersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/point/repository/PointOptionJpaRepository.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/point/PointWebAdapter.kt
Labels: feat

#260 merge: (#259) remainRecord -> remainStatus
  dms-domain/src/main/kotlin/team/aliens/dms/domain/remain/model/RemainStatus.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/remain/entity/RemainStatusJpaEntity.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/remain/mapper/RemainStatusMapper.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/remain/repository/RemainStatusJpaRepository.kt
Labels: setting

#253 merge: (#237) 상벌점 항목 생성&삭제
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/dto/CreatePointOptionRequest.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/dto/CreatePointOptionResponse.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/exception/PointOptionNameExistsException.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/spi/CommandPointOptionPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/spi/PointOptionPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/spi/QueryPointOptionPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/usecase/CreatePointOptionUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/usecase/RemovePointOptionUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/point.usecase/CreatePointOptionUseCaseTest.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/point.usecase/RemovePointOptionUseCaseTest.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/point/error/PointOptionErrorCode.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/point/PointOptionPersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/point/repository/PointOptionJpaRepository.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/point/PointWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/point/dto/request/CreatePointOptionWebRequest.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/point/dto/request/WebPointType.kt
Labels: feat

#252 merge: (#251) 상벌점 내역 엑셀 출력 api
  dms-application/src/main/kotlin/team/aliens/dms/domain/file/spi/ParseFilePort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/file/spi/WriteFilePort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/dto/ExportAllPointHistoryResponse.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/spi/PointQuerySchoolPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/spi/QueryPointHistoryPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/usecase/ExportAllPointHistoryUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/school/spi/SchoolPort.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/point.usecase/ExportAllPointHistoryUseCaseTests.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/file/model/File.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/point/model/PointType.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/point/PointHistoryPersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/parser/ExcelAdapter.kt
  dms-infrastructure/src/test/kotlin/team/aliens/dms/thirdparty/parser/ExcelAdapterTests.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/point/PointWebAdapter.kt
Labels: feat

#257 merge: (#256) 학생 상벌점 내역 조회api
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/dto/PointHistoryDto.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/dto/QueryPointHistoryResponse.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/dto/QueryStudentPointHistoryResponse.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/spi/QueryPointHistoryPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/usecase/QueryPointHistoryUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/usecase/QueryStudentPointHistoryUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/point.usecase/QueryPointHistoryUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/point.usecase/QueryStudentPointHistoryUseCaseTest.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/point/PointHistoryPersistenceAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/point/PointWebAdapter.kt
Labels: feat

#247 merge: (#234) 잔류 신청 시간 설정 API
  dms-application/src/main/kotlin/team/aliens/dms/domain/remain/dto/UpdateRemainAvailableTimeRequest.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/remain/spi/CommandRemainAvailableTimePort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/remain/spi/QueryRemainAvailableTimePort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/remain/spi/RemainAvailableTimePort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/remain/usecase/UpdateRemainAvailableTimeUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/remain/usecase/UpdateRemainAvailableTimeUseCaseTests.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/remain/model/RemainAvailableTime.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/remain/RemainAvailableTimePersistenceAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/remain/RemainWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/remain/dto/request/UpdateRemainAvailableTimeWebRequest.kt
Labels: feat

#265 merge: (#264) 잔류 항목 삭제 api
  dms-application/src/main/kotlin/team/aliens/dms/domain/remain/spi/CommandRemainOptionPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/remain/spi/CommandRemainStatusPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/remain/spi/RemainStatusPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/remain/usecase/RemoveRemainOptionUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/remain/usecase/RemoveRemainOptionUseCaseTests.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/remain/RemainOptionPersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/remain/RemainStatusPersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/remain/repository/RemainStatusJpaRepository.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/remain/RemainWebAdapter.kt
Labels: feat

#258 merge: (#248) 잔류 신청 시간 보기 API
  dms-application/src/main/kotlin/team/aliens/dms/domain/remain/dto/QueryRemainAvailableTimeResponse.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/remain/exception/RemainAvailableTimeCanNotAccessException.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/remain/exception/RemainAvailableTimeNotFoundException.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/remain/exception/RemainOptionNotFoundException.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/remain/usecase/QueryRemainAvailableTimeUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/remain/usecase/QueryRemainAvailableTimeUseCaseTests.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/remain/error/.gitkeep
  dms-domain/src/main/kotlin/team/aliens/dms/domain/remain/error/RemainAvailableTimeErrorCode.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/remain/model/RemainAvailableTime.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/remain/RemainWebAdapter.kt
Labels: feat

#263 merge: (#261) 학생 잔류 신청내역 엑셀 출력 api
  dms-application/src/main/kotlin/team/aliens/dms/domain/file/spi/WriteFilePort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/remain/dto/RemainStatusInfo.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/remain/dto/StudentRemainInfo.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/remain/dto/response/ExportRemainStatusResponse.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/remain/spi/QueryRemainStatusPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/remain/spi/RemainQuerySchoolPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/remain/spi/RemainQueryStudentPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/remain/spi/RemainStatusPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/remain/usecase/ExportRemainStatusUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/school/spi/SchoolPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/spi/StudentPort.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/remain/usecase/ExportRemainStatusUseCaseTests.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/student/model/Sex.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/remain/RemainStatusPersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/remain/repository/vo/RemainStatusInfoVO.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/parser/ExcelAdapter.kt
  dms-infrastructure/src/test/kotlin/team/aliens/dms/thirdparty/parser/ExcelAdapterTests.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/remain/RemainWebAdapter.kt
Labels: feat

#266 merge: (#262) 잔류 신청 항목 목록 보기 API
  dms-application/src/main/kotlin/team/aliens/dms/domain/remain/dto/QueryRemainOptionsResponse.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/remain/spi/QueryRemainOptionPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/remain/spi/QueryRemainStatusPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/remain/spi/RemainAvailableTimePort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/remain/spi/RemainOptionPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/remain/spi/RemainStatusPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/remain/usecase/QueryRemainOptionsUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/remain/usecase/QueryRemainOptionsUseCaseTests.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/remain/RemainOptionPersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/remain/RemainStatusPersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/remain/repository/RemainOptionJpaRepository.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/remain/RemainWebAdapter.kt
Labels: feat

#268 merge: (#267) 내 잔류 신청항목 보기 API
  dms-application/src/main/kotlin/team/aliens/dms/domain/remain/dto/QueryCurrentAppliedRemainOptionResponse.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/remain/exception/RemainStatusNotFound.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/remain/usecase/QueryCurrentAppliedRemainOptionUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/remain/usecase/QueryCurrentAppliedRemainOptionUseCaseTests.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/remain/error/RemainStatusErrorCode.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/remain/RemainWebAdapter.kt
Labels: feat

#272 merge: (#269) 잔류 신청 api
  dms-application/src/main/kotlin/team/aliens/dms/domain/remain/exception/RemainCanNotAppliedException.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/remain/spi/CommandRemainStatusPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/remain/usecase/ApplyRemainUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/remain/usecase/ApplyRemainUseCaseTests.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/remain/error/RemainAvailableTimeErrorCode.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/remain/RemainStatusPersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/remain/entity/RemainStatusJpaEntity.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/remain/RemainWebAdapter.kt
Labels: feat

#274 merge: (#273) 상벌점 항목 변경
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/usecase/CreatePointOptionUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/point/usecase/UpdatePointOptionUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/point.usecase/UpdatePointOptionUseCaseTest.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/point/PointWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/point/dto/request/UpdatePointOptionWebRequest.kt
Labels: feat

#277 merge: (#276) remainService 추가
  dms-application/src/main/kotlin/team/aliens/dms/domain/auth/dto/SignInResponse.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/auth/usecase/SignInUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/auth/usecase/ReissueTokenUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/auth/usecase/SignInUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/student/usecase/SignUpUseCaseTests.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/school/model/AvailableFeature.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/school/entity/AvailableFeatureJpaEntity.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/school/mapper/AvailableFeatureMapper.kt
Labels: feat

#279 merge: (#278) 학생 탈퇴 api
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/spi/ManagerCommandRemainStatusPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/spi/ManagerCommandStudentPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/spi/ManagerCommandStudyRoomPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/spi/ManagerQueryStudyRoomPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/usecase/RemoveStudentUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/remain/spi/RemainStatusPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/spi/StudentCommandRemainStatusPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/spi/StudentCommandStudyRoomPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/spi/StudentPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/spi/StudentQueryStudyRoomPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/usecase/StudentWithdrawalUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/exception/AppliedSeatNotFoundException.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/StudyRoomPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/QueryCurrentAppliedStudyRoomUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/UnApplySeatUseCase.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/manager/usecase/RemoveStudentUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/student/usecase/StudentWithdrawalUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/studyroom/usecase/QueryCurrentAppliedStudyRoomUseCaseTests.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/remain/RemainStatusPersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/remain/repository/RemainStatusJpaRepository.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/student/StudentWebAdapter.kt
Labels: feat

#288 merge: (#287) 호실번호 타입 변경
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/dto/GetStudentDetailsResponse.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/dto/QueryStudentsResponse.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/spi/ManagerQueryStudentPort.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/remain/dto/StudentRemainInfo.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/student/spi/StudentQueryRoomPort.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/manager/usecase/QueryStudentDetailsUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/manager/usecase/QueryStudentsUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/manager/usecase/RemoveStudentUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/meal/usecase/QueryMealsUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/point.usecase/QueryPointHistoryUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/point.usecase/QueryStudentPointHistoryUseCaseTest.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/remain/usecase/ExportRemainStatusUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/student/usecase/CheckStudentGcnUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/student/usecase/FindStudentAccountIdUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/student/usecase/ResetStudentPasswordUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/student/usecase/SignUpUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/student/usecase/StudentMyPageUseCaseTests.kt
  dms-application/src/test/kotlin/team/aliens/dms/domain/student/usecase/UpdateStudentProfileUseCaseTests.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/room/model/Room.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/student/model/Student.kt
  dms-domain/src/main/kotlin/team/aliens/dms/domain/student/model/VerifiedStudent.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/room/RoomPersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/room/entity/RoomJpaEntity.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/room/repository/RoomJpaRepository.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/entity/VerifiedStudentJpaEntity.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/parser/ExcelAdapter.kt
  dms-infrastructure/src/test/kotlin/team/aliens/dms/thirdparty/parser/ExcelAdapterTests.kt
Labels: refactor

#293 merge: (#292) 학생목록검색 필터타입 변경
  dms-application/src/main/kotlin/team/aliens/dms/domain/file/usecase/UploadFileUseCase.kt
  dms-application/src/main/kotlin/team/aliens/dms/domain/manager/dto/PointFilterType.kt
Labels: refactor

#296 merge: (#295) JPA Dialect 변경
  dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/BaseTimeEntity.kt
  dms-infrastructure/src/main/resources/application.yml
Labels: setting
