Repository team-aliens/DMS-Backend, pull requests merged in 2024-04, with the labels that each got.

#599 merge: (#598) 외출 상태 추가
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/dto/OutingResponse.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/model/OutingStatus.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/usecase/ApplyOutingUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/usecase/GetOutingHistoryDetailsUseCase.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/OutingApplicationPersistenceAdapter.kt
Labels: feat

#604 merge: (#603) 현재 외출 신청 id 반환
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/dto/OutingResponse.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/spi/vo/CurrentOutingApplicationVO.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/OutingApplicationPersistenceAdapter.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/repository/vo/QueryCurrentOutingApplicationVO.kt
Labels: feat

#606 chore: (#605) 외출 취소 확인 로직 변경
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/model/OutingApplication.kt
  dms-core/src/test/kotlin/team/aliens/dms/domain/outing/model/OutingApplicationTest.kt
Labels: feat

#607 feat: (#602) 벌점 태그 자동 부여 스케줄러 추가
  dms-core/src/main/kotlin/team/aliens/dms/domain/point/service/GetPointService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/point/service/GetPointServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/point/spi/QueryPointHistoryPort.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/point/spi/vo/StudentTotalVO.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/student/service/GetStudentService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/student/service/GetStudentServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/tag/model/WarningTag.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/tag/service/CommandTagService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/tag/service/CommandTagServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/tag/service/GetTagService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/tag/service/GetTagServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/tag/spi/CommandStudentTagPort.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/tag/spi/QueryStudentTagPort.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/tag/spi/QueryTagPort.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/tag/spi/StudentTagPort.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/tag/usecase/UpdateStudentTagsUseCase.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/scheduler/StudentTagScheduler.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/point/PointHistoryPersistenceAdapter.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/point/repository/vo/QueryStudentTotalVO.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/tag/StudentTagPersistenceAdapter.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/tag/TagPersistenceAdapter.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/tag/repository/StudentTagJpaRepository.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/tag/repository/TagJpaRepository.kt
Labels: feat

#613 merge: (#611) 외출 검색 로직 변경
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/OutingApplicationPersistenceAdapter.kt
Labels: refactor

#617 merge: (#616) flyway 추가
  dms-infrastructure/src/main/resources/db/migration/V3__update_out_at_to_outing_date.sql
  dms-infrastructure/src/main/resources/db/migration/V4__add_outingService_in_to_tbl_available_feature.sql
Labels: chore

#619 fix: (#616) 외출 신청 조건 변경
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/service/CheckOutingServiceImpl.kt
Labels: 👾bug
