Repository team-aliens/DMS-Backend, pull requests merged in 2024-09, with the labels that each got.

#727 merge: (#711) nullable & null체크 추가
  dms-core/src/main/kotlin/team/aliens/dms/domain/auth/dto/SignInRequest.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/auth/usecase/SignInUseCase.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/auth/dto/request/SignInWebRequest.kt
Labels: refactor

#730 merge: (#729) 로그인 device token blank 체크 추가
  dms-core/src/main/kotlin/team/aliens/dms/domain/auth/usecase/SignInUseCase.kt
Labels: refactor

#732 merge: 봉사, 봉사 신청 엔티티 매핑
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/model/GradeCondition.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/model/Volunteer.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/model/VolunteerApplication.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/volunteer/entity/VolunteerApplicationJpaEntity.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/volunteer/entity/VolunteerJpaEntity.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/volunteer/mapper/VolunteerApplicationMapper.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/volunteer/mapper/VolunteerMapper.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/volunteer/repository/VolunteerApplicationJpaRepository.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/volunteer/repository/VolunteerJpaRepository.kt
Labels: feat

#735 merge: (#734) 봉사 신청 approved 컬럼 추가
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/model/VolunteerApplication.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/volunteer/entity/VolunteerApplicationJpaEntity.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/volunteer/mapper/VolunteerApplicationMapper.kt
Labels: feat

#739 merge: (#738) 봉사 schoolId 컬럼 추가
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/model/Volunteer.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/volunteer/entity/VolunteerJpaEntity.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/volunteer/mapper/VolunteerMapper.kt
Labels: feat

#741 merge: 740 flyway 스크립트 작성
  dms-infrastructure/src/main/resources/db/migration/V4__create_tbl_volunteer_and_attachment.sql
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/volunteer/entity/VolunteerApplicationJpaEntity.kt
Labels: feat

#742 feat: (#737) 캐싱 적용
  buildSrc/src/main/kotlin/Dependencies.kt
  dms-infrastructure/build.gradle.kts
  dms-persistence/src/main/kotlin/team/aliens/dms/global/config/CacheConfig.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/global/config/CustomKeyGenerator.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/volunteer/repository/VolunteerApplicationJpaRepository.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/volunteer/repository/VolunteerJpaRepository.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/student/StudentWebAdapter.kt
Labels: feat

#746 merge: (#745) 토큰 시간 변경
  dms-infrastructure/src/main/resources/application.yml
Labels: chore

#743 merge: (#733) 봉사 신청/ 관리 API
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/dto/request/CreateVolunteerRequest.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/dto/request/UpdateVolunteerRequest.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/dto/response/ApplyVolunteerResponse.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/dto/response/VolunteerResponse.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/exception/VolunteerErrorCode.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/exception/VolunteerExceptions.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/model/GradeCondition.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/model/Volunteer.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/model/VolunteerApplication.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/service/CommandVolunteerService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/service/CommandVolunteerServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/service/GetVolunteerService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/service/GetVolunteerServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/service/VolunteerService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/spi/CommandVolunteerApplicationPort.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/spi/CommandVolunteerPort.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/spi/QueryVolunteerApplicationPort.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/spi/QueryVolunteerPort.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/spi/VolunteerApplicationPort.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/spi/VolunteerPort.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/spi/vo/CurrentVolunteerApplicantVO.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/spi/vo/VolunteerApplicantVO.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/usecase/ApplyVolunteerUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/usecase/ApproveVolunteerApplicationUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/usecase/CreateVolunteerUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/usecase/DeleteVolunteerUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/usecase/ExcludeVolunteerApplicationUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/usecase/ManagerGetAllVolunteersUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/usecase/QueryAppliedStudentUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/usecase/QueryAvailableVolunteersUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/usecase/QueryCurrentVolunteerApplicantsUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/usecase/QueryMyVolunteerApplicationUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/usecase/RejectVolunteerApplicationUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/usecase/UnapplyVolunteerUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/usecase/UpdateVolunteerUseCase.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfig.kt
  dms-infrastructure/src/main/resources/db/migration/V5__change_column_name_in_tbl_volunteer.sql
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/volunteer/VolunteerApplicationPersistenceAdapter.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/volunteer/VolunteerPersistenceAdapter.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/volunteer/entity/VolunteerJpaEntity.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/volunteer/mapper/VolunteerMapper.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/volunteer/repository/VolunteerApplicationJpaRepository.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/volunteer/repository/VolunteerJpaRepository.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/volunteer/repository/vo/QueryCurrentVolunteerApplicantVO.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/volunteer/repository/vo/QueryVolunteerApplicantVO.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/volunteer/VolunteerWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/volunteer/dto/request/CreateVolunteerWebRequest.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/volunteer/dto/request/UpdateVolunteerWebRequest.kt
Labels: feat

#748 merge: (#747) 외출 제약 조건 수정
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/model/OutingAvailableTime.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/service/CheckOutingServiceImpl.kt
  dms-core/src/test/kotlin/team/aliens/dms/domain/outing/model/OutingAvailableTimeTest.kt
Labels: chore

#751 merge: (#750) 캐시 적용 에러 해결
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/service/CheckOutingServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/student/dto/StudentResponse.kt
Labels: 👾bug

#756 merge: (#749) 외출 엑셀 수정
  dms-core/src/main/kotlin/team/aliens/dms/domain/file/service/WriteFileService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/file/service/WriteFileServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/file/spi/WriteFilePort.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/service/GetOutingServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/spi/vo/OutingApplicationVO.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/usecase/ExportAllOutingApplicationsUseCase.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/parser/ExcelAdapter.kt
  dms-infrastructure/src/main/resources/application.yml
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/OutingApplicationPersistenceAdapter.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/repository/vo/QueryOutingApplicationVO.kt
Labels: chore

#755 merge: (#754) 학생 전체 조회 오류 수정
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/student/StudentWebAdapter.kt
Labels: 👾bug

#758 refactor: (#757) Jackson 생성자 지정
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/service/GetOutingServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/student/dto/StudentResponse.kt
Labels: 👾bug

#762 merge: (#761) 캐시 삭제
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/student/StudentWebAdapter.kt
Labels: 👾bug

#764 merge: (#763) 학생 목록 검색 에러 해결
  buildSrc/src/main/kotlin/Dependencies.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/student/dto/StudentResponse.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/tag/dto/TagResponse.kt
  dms-infrastructure/build.gradle.kts
  dms-persistence/src/main/kotlin/team/aliens/dms/global/config/CacheConfig.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/global/config/CustomKeyGenerator.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/student/StudentWebAdapter.kt
Labels: 👾bug

#760 merge: (#759) null 방지 추가
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/spi/vo/OutingApplicationVO.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/parser/ExcelAdapter.kt
  dms-infrastructure/src/main/resources/application-local.yml
Labels: 👾bug

#768 merge: (#767) reason nullable
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/spi/vo/OutingApplicationVO.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/parser/ExcelAdapter.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/OutingApplicationPersistenceAdapter.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/repository/vo/QueryOutingApplicationVO.kt
Labels: 👾bug

#776 merge: (#770) 외출 조회 제약조건
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/service/CheckOutingService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/service/CheckOutingServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/service/GetOutingServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/usecase/GetCurrentOutingApplicationUseCase.kt
Labels: chore
