Repository team-aliens/DMS-Backend, pull requests merged in 2024-05, with the labels that each got.

#621 feat: (#609) 버그 제보 기능 추가
  dms-core/src/main/kotlin/team/aliens/dms/domain/bug/dto/CreateBugReportRequest.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/bug/model/BugAttachment.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/bug/model/BugReport.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/bug/model/DevelopmentArea.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/bug/service/BugService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/bug/service/CommandBugService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/bug/service/CommandBugServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/bug/spi/BugPort.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/bug/spi/CommandBugPort.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/bug/usecase/CreateBugReportUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/service/CheckOutingServiceImpl.kt
  dms-core/src/test/kotlin/team/aliens/dms/domain/bug/stub/BugStub.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfig.kt
  dms-infrastructure/src/main/resources/db/migration/V5_create_tbl_bug_report&attachment.sql
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/bug/BugPersistenceAdapter.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/bug/entity/BugAttachmentJpaEntity.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/bug/entity/BugReportJpaEntity.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/bug/mapper/BugReportMapper.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/bug/repository/BugJpaRepository.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/bug/BugWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/bug/dto/CreateBugReportWebRequest.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/bug/dto/DevelopmentArea.kt
Labels: feat

#620 merge: (#610) 학생 태그 스케줄러 api 수정
  dms-core/src/main/kotlin/team/aliens/dms/domain/tag/model/WarningTag.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/tag/service/CommandTagService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/tag/service/CommandTagServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/tag/service/GetTagService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/tag/service/GetTagServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/tag/spi/CommandStudentTagPort.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/tag/spi/QueryStudentTagPort.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/tag/spi/QueryTagPort.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/tag/spi/vo/StudentTagDetailVO.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/tag/usecase/UpdateStudentTagsUseCase.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/point/PointHistoryPersistenceAdapter.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/tag/StudentTagPersistenceAdapter.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/tag/TagPersistenceAdapter.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/tag/repository/StudentTagJpaRepository.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/tag/repository/vo/QueryStudentTagDetailVO.kt
Labels: 👾bug

#623 fix: (#622) flyway 삭제
  dms-infrastructure/src/main/resources/db/migration/V5_create_tbl_bug_report&attachment.sql
Labels: 👾bug

#626 merge: (#624) sql 파일명 수정
  dms-infrastructure/src/main/resources/db/migration/V3__create_tbl_bug_report_and_attachment.sql
Labels: chore

#627 chore: (#625) 내 외출 신청 조회 수정
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/OutingApplicationPersistenceAdapter.kt
Labels: chore

#633 chore: (#632) 로직 수정
  dms-core/src/main/kotlin/team/aliens/dms/domain/tag/model/WarningTag.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/tag/usecase/UpdateStudentTagsUseCase.kt
Labels: chore

#639 chore: (#637) 폭 넓이 수정
  dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/parser/ExcelAdapter.kt
Labels: chore

#641 merge: (#640) 외출 가능 시간 삭제 API
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/dto/response/SetOutingAvailableTimeResponse.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/exception/OutingErrorCode.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/exception/OutingExceptions.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/service/CheckOutingServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/service/CommandOutingService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/service/CommandOutingServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/service/GetOutingService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/service/GetOutingServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/spi/CommandOutingTimePort.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/spi/QueryOutingAvailableTimePort.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/usecase/RemoveOutingAvailableTimeUseCase.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfig.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/OutingAvailableTimePersistenceAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/outing/OutingWebAdapter.kt
Labels: feat
