Repository team-aliens/DMS-Backend, pull requests merged in 2024-06, with the labels that each got.

#650 merge: (#649) 외출 가능 시간 활성화 여부 변경
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/model/OutingAvailableTime.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/usecase/ToggleOutingAvailableTimeUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/usecase/UpdateOutingAvailableTimeUseCase.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfig.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/outing/OutingWebAdapter.kt
Labels: feat

#656 merge: (#655) 변수 임시 수정
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/dto/request/SetOutingTimeRequest.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/usecase/SetOutingAvailableTimeUseCase.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/outing/OutingWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/outing/dto/request/SetOutingAvailableTimeWebRequest.kt
Labels: 🤔defer

#661 merge: (#660) fcm 환경변수 추가
  .github/workflows/xquare-cd-dev.yml
  .github/workflows/xquare-cd-prod.yml
  Dockerfile
Labels: feat

#662 merge: (#638) FCM 주석 제거
  dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/notification/FCMConfig.kt
Labels: feat

#659 merge: (#657) 외출 신청 중복 예외처리
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/service/CheckOutingServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/spi/QueryOutingCompanionPort.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/OutingCompanionsPersistenceAdapter.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/repository/OutingCompanionJpaRepository.kt
Labels: feat

#664 merge: (#658) 동행자 외출 신청 내역 조회 버그
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/service/GetOutingService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/service/GetOutingServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/spi/QueryOutingApplicationPort.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/usecase/GetCurrentOutingApplicationUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/student/service/GetStudentService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/student/service/GetStudentServiceImpl.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/OutingApplicationPersistenceAdapter.kt
Labels: 👾bug

#667 merge: (#666) 변수명 재수정
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/dto/request/SetOutingTimeRequest.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/usecase/SetOutingAvailableTimeUseCase.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/outing/OutingWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/outing/dto/request/SetOutingAvailableTimeWebRequest.kt
Labels: chore

#669 merge: (#668) 컬럼 넓이 수정 로직 추가
  dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/parser/ExcelAdapter.kt
Labels: chore
