Repository team-aliens/DMS-Backend, pull requests merged in 2024-10, with the labels that each got.

#778 merge: (#777) volunteer service 추가
  dms-core/src/main/kotlin/team/aliens/dms/domain/school/dto/SchoolResponse.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/school/model/AvailableFeature.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/school/usecase/QueryAvailableFeaturesUseCase.kt
  dms-core/src/test/kotlin/team/aliens/dms/domain/school/stub/SchoolStub.kt
  dms-infrastructure/src/main/resources/db/migration/V7__add_column_in_tbl_available_feature.sql
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/school/entity/AvailableFeatureJpaEntity.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/school/mapper/AvailableFeatureMapper.kt
Labels: feat

#775 merge: (#774) 봉사 활동 목록 조회 Response 에 CurrentApplicants 추가
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/dto/response/VolunteerResponse.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/model/VolunteerApplicationStatus.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/service/GetVolunteerService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/service/GetVolunteerServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/spi/QueryVolunteerApplicationPort.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/spi/QueryVolunteerPort.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/spi/vo/CurrentVolunteerApplicantVO.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/spi/vo/VolunteerWithCurrentApplicantVO.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/usecase/ManagerGetAllVolunteersUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/usecase/QueryAvailableVolunteersUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/usecase/UnapplyVolunteerUseCase.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfig.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/volunteer/VolunteerApplicationPersistenceAdapter.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/volunteer/VolunteerPersistenceAdapter.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/volunteer/repository/vo/QueryCurrentVolunteerApplicantVO.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/volunteer/repository/vo/QueryVolunteerWithCurrentApplicantVO.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/volunteer/VolunteerWebAdapter.kt
Labels: feat

#782 merge: (#780) CD 빌드 오류 해결
  build.gradle.kts
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfig.kt
Labels: 👾bug

#784 merge: (#783) id 필드 추가 및 name 필드 명 변경
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/dto/response/VolunteerResponse.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/spi/vo/CurrentVolunteerApplicantVO.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/volunteer/VolunteerApplicationPersistenceAdapter.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/volunteer/repository/vo/QueryCurrentVolunteerApplicantVO.kt
Labels: chore

#787 merge: (#785) volunteer content 삭제
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/service/CheckOutingService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/service/GetOutingServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/dto/request/CreateVolunteerRequest.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/dto/request/UpdateVolunteerRequest.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/dto/response/VolunteerResponse.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/model/Volunteer.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/spi/vo/VolunteerWithCurrentApplicantVO.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/usecase/CreateVolunteerUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/usecase/UpdateVolunteerUseCase.kt
  dms-core/src/test/kotlin/team/aliens/dms/domain/school/stub/SchoolStub.kt
  dms-infrastructure/src/main/resources/db/migration/V8__delete_column_in_tbl_volunteer.sql
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/volunteer/VolunteerPersistenceAdapter.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/volunteer/entity/VolunteerJpaEntity.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/volunteer/mapper/VolunteerMapper.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/volunteer/repository/vo/QueryVolunteerWithCurrentApplicantVO.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/volunteer/VolunteerWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/volunteer/dto/request/CreateVolunteerWebRequest.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/volunteer/dto/request/UpdateVolunteerWebRequest.kt
Labels: refactor

#789 merge: (#786) 수락된 신청자 수 표시 버그 수정
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/service/GetVolunteerServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/spi/QueryVolunteerPort.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/volunteer/VolunteerPersistenceAdapter.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/volunteer/repository/vo/QueryVolunteerWithCurrentApplicantVO.kt
Labels: 👾bug

#790 merge: (#788) 외출 내역 조회 API 변경
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/dto/response/OutingResponse.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/model/OutingApplication.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/model/OutingStatus.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/service/GetOutingService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/service/GetOutingServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/spi/QueryOutingApplicationPort.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/spi/vo/CurrentOutingApplicationVO.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/spi/vo/OutingApplicationVO.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/spi/vo/OutingHistoryVO.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/usecase/ApplyOutingUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/usecase/ExportAllOutingApplicationsUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/usecase/GetOutingApplicationHistoriesUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/usecase/UnApplyOutingUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/usecase/UpdateOutingStatusUseCase.kt
  dms-core/src/test/kotlin/team/aliens/dms/domain/outing/model/OutingApplicationTest.kt
  dms-core/src/test/kotlin/team/aliens/dms/domain/outing/stub/OutingStub.kt
  dms-infrastructure/src/main/resources/db/migration/V9__change_column_in_table_outinga_application.sql
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/OutingApplicationPersistenceAdapter.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/entity/OutingApplicationJpaEntity.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/mapper/OutingApplicationMapper.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/repository/vo/QueryCurrentOutingApplicationVO.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/repository/vo/QueryOutingApplicationVO.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/repository/vo/QueryOutingHistoryVO.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/outing/OutingWebAdapter.kt
Labels: feat

#792 merge: (#791) 내 외출 신청 오늘만 조회되도록 변경
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/service/GetOutingServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/spi/QueryOutingApplicationPort.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/OutingApplicationPersistenceAdapter.kt
Labels: chore
