Repository team-aliens/DMS-Backend, pull requests merged in 2024-08, with the labels that each got.

#700 merge: (#697) 알림조회 페이징 처리 삭제
  dms-core/src/main/kotlin/team/aliens/dms/domain/notification/service/GetNotificationService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/notification/service/GetNotificationServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/notification/spi/QueryNotificationOfUserPort.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/notification/usecase/QueryAndReadMyNotificationsUseCase.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfig.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/notification/NotificationOfPersistenceAdapterOfUser.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/notification/NotificationWebAdapter.kt
Labels: chore

#699 merge: (#695) 알림 구독여부 기본값 수정
  dms-core/src/main/kotlin/team/aliens/dms/domain/notification/dto/TopicSubscriptionResponse.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/notification/usecase/QueryTopicSubscriptionUseCase.kt
Labels: chore

#706 merge: publishNotificationToApplicant 사용으로 변경
  dms-core/src/main/kotlin/team/aliens/dms/domain/point/service/CommandPointServiceImpl.kt
Labels: 👾bug

#707 merge: (#705) 외출 신청 동행자 알람 미발행 버그 수정
  dms-core/src/main/kotlin/team/aliens/dms/domain/notification/spi/QueryDeviceTokenPort.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/service/CommandOutingServiceImpl.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/notification/DeviceTokenPersistenceAdapter.kt
Labels: 👾bug

#710 merge: (#709) 상벌점 부여시 알람 발송 로직 수정
  dms-core/src/main/kotlin/team/aliens/dms/domain/notification/spi/QueryDeviceTokenPort.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/service/CommandOutingServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/point/service/CommandPointService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/point/service/CommandPointServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/point/usecase/GrantPointUseCase.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/notification/DeviceTokenPersistenceAdapter.kt
Labels: 👾bug

#713 meage: (#712) banner 적용
  dms-infrastructure/src/main/resources/banner.txt
Labels: docs

#715 merge: (#714) notification 분리
  dms-core/src/main/kotlin/team/aliens/dms/common/spi/EventPort.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/notice/service/CommandNoticeServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/notification/spi/QueryDeviceTokenPort.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/event/EventAdapter.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/notification/DeviceTokenPersistenceAdapter.kt
Labels: feat

#717 merge: (#716) 학생 조회 api 에 schoolId 추가
  dms-core/src/main/kotlin/team/aliens/dms/domain/student/service/GetStudentService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/student/service/GetStudentServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/student/spi/QueryStudentPort.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/student/usecase/StudentGetAllStudentsUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/tag/service/CommandTagService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/tag/service/CommandTagServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/tag/service/GetTagService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/tag/service/GetTagServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/tag/spi/CommandStudentTagPort.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/tag/spi/QueryStudentTagPort.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/tag/spi/QueryTagPort.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/tag/StudentTagPersistenceAdapter.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/tag/TagPersistenceAdapter.kt
Labels: 👾bug

#720 merge: (#719) 외출 가능 시간 수정 버그
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/usecase/UpdateOutingAvailableTimeUseCase.kt
Labels: 👾bug

#723 merge: (#719) 알림 구독/해제 API 병합
  dms-core/src/main/kotlin/team/aliens/dms/domain/notification/service/NotificationService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/notification/service/NotificationServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/notification/spi/QueryTopicSubscriptionPort.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/notification/usecase/ToggleSubscriptionUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/student/service/GetStudentServiceImpl.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfig.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/notification/TopicSubscriptionPersistenceAdapter.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/notification/repository/TopicSubscriptionJpaRepository.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/notification/NotificationWebAdapter.kt
Labels: feat

#726 chore: (#725) 빌드 배너 변경
  dms-infrastructure/src/main/resources/banner.txt
Labels: chore

#724 merge: (#672) 서버 버그 발생시 slack 으로 메세지 송신
  .github/workflows/xquare-cd-dev.yml
  .github/workflows/xquare-cd-prod.yml
  Dockerfile
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/DependencyVersions.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/bug/service/BugService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/bug/service/SendBugService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/bug/service/SendBugServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/bug/spi/SendBugPort.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/bug/usecase/CreateBugReportUseCase.kt
  dms-infrastructure/build.gradle.kts
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/filter/ExceptionFilter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/filter/FilterConfig.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/slack/SlackAdapter.kt
  dms-infrastructure/src/main/resources/application.yml
Labels: feat
