Repository team-aliens/DMS-Backend, pull requests merged in 2024-07, with the labels that each got.

#665 merge: (#663) 로그인에 deviceToken 등록 추가
  dms-core/src/main/kotlin/team/aliens/dms/domain/auth/dto/SignInRequest.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/auth/usecase/SignInUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/notification/service/CheckNotificationService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/notification/service/CheckNotificationServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/notification/service/CommandNotificationService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/notification/service/CommandNotificationServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/notification/service/NotificationService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/notification/service/NotificationServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/notification/spi/QueryDeviceTokenPort.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/notification/DeviceTokenPersistenceAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/auth/AuthWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/auth/dto/request/SignInWebRequest.kt
Labels: feat

#674 merge: (#673) flyway 환경 변수 추가
  dms-infrastructure/src/main/resources/application.yml
Labels: feat

#676 merge: (#673) dockerfile 환경 변수 추가
  .github/workflows/xquare-cd-dev.yml
  .github/workflows/xquare-cd-prod.yml
  Dockerfile
  dms-infrastructure/src/main/resources/application.yml
Labels: chore

#677 merge: (#670) 디바이스 토큰 삭제 에러 수정
  dms-core/src/main/kotlin/team/aliens/dms/domain/notification/service/CommandNotificationService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/notification/service/CommandNotificationServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/notification/spi/CommandTopicSubscriptionPort.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/notification/DeviceTokenPersistenceAdapter.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/notification/TopicSubscriptionPersistenceAdapter.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/notification/repository/DeviceTokenJpaRepository.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/notification/repository/TopicSubscriptionJpaRepository.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/auth/dto/request/SignInWebRequest.kt
Labels: 👾bug

#684 merge: (#682) 상벌점 알림 토픽 추가
  dms-core/src/main/kotlin/team/aliens/dms/domain/notification/model/Notification.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/notification/model/Topic.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/point/model/PointHistory.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/point/service/CommandPointServiceImpl.kt
Labels: feat

#686 merge: (#683) 외출 알림 추가
  dms-core/src/main/kotlin/team/aliens/dms/common/spi/EventPort.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/notification/model/Notification.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/notification/model/Topic.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/service/CommandOutingServiceImpl.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/event/EventAdapter.kt
Labels: feat

#688 merge: (#687) 알림 삭제 스케줄러
  dms-core/src/main/kotlin/team/aliens/dms/domain/notification/service/CommandNotificationService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/notification/service/CommandNotificationServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/notification/spi/CommandNotificationOfUserPort.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/notification/usecase/DeleteOldNotificationsUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/service/CommandOutingServiceImpl.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/scheduler/NotificationScheduler.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/notification/NotificationOfPersistenceAdapterOfUser.kt
Labels: feat

#692 merge: (#691) 외출 알림 버그 수정
  dms-core/src/main/kotlin/team/aliens/dms/domain/notification/model/Notification.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/notification/model/Topic.kt
Labels: 👾bug

#696 merge: (#671) 엑셀 API 메서드 분리
  dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/parser/ExcelAdapter.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/parser/port/ExcelPort.kt
Labels: refactor

#681 merge: (#679) 동행자가 내 외출 신청 조회 쿼리 버그 수정
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/dto/response/OutingResponse.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/service/GetOutingService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/service/GetOutingServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/spi/QueryOutingApplicationPort.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/spi/vo/CurrentOutingApplicationVO.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/outing/usecase/GetCurrentOutingApplicationUseCase.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfig.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/OutingApplicationPersistenceAdapter.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/repository/vo/QueryCurrentOutingApplicationVO.kt
Labels: 👾bug

#702 merge: (#701) device_token으로 이름 변경
  dms-core/src/main/kotlin/team/aliens/dms/domain/notification/usecase/SubscribeTopicUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/notification/usecase/UnsubscribeTopicUseCase.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/notification/NotificationWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/notification/dto/request/TopicRequest.kt
Labels: chore
