Repository team-aliens/DMS-Backend, pull requests merged in 2025-03, with the labels that each got.

#817 merge: (#816) Windows에서 파일 이름에 사용할 수 없는 문자 변경
  dms-presentation/src/main/kotlin/team/aliens/dms/common/extension/FileExtension.kt
Labels: 👾bug

#803 merge: (#798) 모범학생 후보 리스트 조회 기능 추가
  dms-core/src/main/kotlin/team/aliens/dms/domain/student/service/GetStudentService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/student/service/GetStudentServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/student/spi/QueryStudentPort.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/student/spi/vo/ModelStudentVO.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/student/usecase/GetModelStudentsUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/dto/request/ModelStudentListRequest.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/dto/response/ModelStudentResponse.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/dto/response/ModelStudentsResponse.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/exception/VoteErrorCode.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/exception/VoteExceptions.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfig.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/student/StudentWebAdapter.kt
Labels: feat

#819 chore: (#818) 쓸모없는 환경변수 제거
  .github/CODEOWNERS
  .github/workflows/xquare-cd-dev.yml
Labels: chore

#822 fix: (#821) flyway 수정
  dms-infrastructure/src/main/resources/db/migration/V10_create_tbl_vote_and_voting_option.sql
  dms-infrastructure/src/main/resources/db/migration/V11_create_tbl_vote_and_voting_option.sql
Labels: 👾bug

#820 merge: (#808) 투표 항목 추가 api 생성
  dms-core/src/main/kotlin/team/aliens/dms/domain/student/service/GetStudentServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/dto/request/CreateVotingOptionRequest.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/exception/VoteErrorCode.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/exception/VoteExceptions.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/exception/error/VoteErrorCode.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/model/VotingTopic.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/service/CheckVoteService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/service/CheckVoteServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/service/CommandVoteService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/service/CommandVoteServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/service/GetVoteService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/service/GetVoteServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/service/VoteService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/spi/CommandVotePort.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/spi/CommandVotingOptionPort.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/spi/CommandVotingTopicPort.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/spi/QueryVotePort.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/spi/QueryVotingOptionPort.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/spi/QueryVotingTopicPort.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/spi/VotingOptionPort.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/spi/VotingTopicPort.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/spi/vo/OptionVotingResultVO.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/spi/vo/StudentVotingResultVO.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/usecase/CreateVotingOptionUseCase.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/vote/VotePersistenceAdapter.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/vote/VotingOptionPersistenceAdapter.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/vote/VotingTopicPersistenceAdapter.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/vote/repository/VotingTopicJpaRepository.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/vote/repository/vo/QueryOptionVotingResultVO.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/vote/repository/vo/QueryStudentVotingResultVO.kt
Labels: feat

#833 merge: (#832) 모범학생 후보에서 제외할 학생 도메인 삭제
  dms-core/src/main/kotlin/team/aliens/dms/domain/student/model/ExcludedStudent.kt
  dms-infrastructure/src/main/resources/db/migration/V13__create_tbl_excluded_student.sql
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/student/entity/ExcludedStudentJpaEntity.kt
Labels: feat

#837 merge: (#836) 컴포넌트 등록
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/vote/VotingOptionPersistenceAdapter.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/vote/VotingTopicPersistenceAdapter.kt
Labels: 👾bug

#828 merge: (#809) 투표 항목 삭제 api 생성
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/service/CommandVoteService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/service/CommandVoteServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/usecase/RemoveVotingOptionUseCase.kt
Labels: feat

#831 merge: (#812) 투표 삭제 api 추가
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/exception/VoteExceptions.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/exception/error/VoteErrorCode.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/service/CommandVoteService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/service/CommandVoteServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/usecase/RemoveVoteUseCase.kt
Labels: feat

#829 merge: (#810) 투표 항목 조회 api
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/dto/response/VotingOption.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/dto/response/VotingOptionsResponse.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/service/GetVoteService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/service/GetVoteServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/spi/QueryVotingOptionPort.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/usecase/QueryVotingOptionsUseCase.kt
Labels: feat

#830 merge: (#811) 표 생성 api
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/usecase/CreateVoteUseCase.kt
Labels: feat

#842 merge: (#813) 투표 결과 조회 api 생성
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/dto/response/VoteResponse.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/dto/response/VotesResponse.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/usecase/CreateVoteUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/usecase/DeleteVoteUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/usecase/DeleteVotingOptionUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/usecase/QueryVotesUseCase.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/vote/VoteWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/vote/dto/request/CreateVotingOptionWebRequest.kt
Labels: feat

#843 merge: (#826) 모범학생 후보에서 제외된 학생 전체 조회 api 추가
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/dto/reponse/VoteResponse.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/service/GetVoteService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/service/GetVoteServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/spi/CommandExcludedStudentPort.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/spi/ExcludedStudentPort.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/spi/QueryExcludedStudentPort.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/usecase/QueryAllExcludedStudentUseCase.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfig.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/vote/ExcludedStudentPersistenceAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/vote/VoteWebAdapter.kt
Labels: feat

#841 merge: (#840) 상벌점 토탈 조회 쿼리 리팩토링
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/point/PointHistoryPersistenceAdapter.kt
Labels: refactor

#847 merge: (#824) 모범학생 후보 제외학생 생성 api 추가
  dms-core/src/main/kotlin/team/aliens/dms/domain/student/model/Student.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/dto/request/CreateExcludedStudentRequest.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/exception/VoteExceptions.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/exception/error/VoteErrorCode.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/service/CheckVoteService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/service/CheckVoteServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/service/CommandVoteService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/service/CommandVoteServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/spi/QueryExcludedStudentPort.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/usecase/CreateExcludedStudentUseCase.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfig.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/vote/ExcludedStudentPersistenceAdapter.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/vote/entity/ExcludedStudentJpaEntity.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/vote/mapper/ExcludedStudentMapper.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/vote/VoteWebAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/vote/dto/request/CreateExcludedStudentWebRequest.kt
Labels: feat

#852 merge: (#851) 마이그레이션 v13 실행안됨 오류 수정
  dms-infrastructure/src/main/resources/db/migration/V13__create_tbl_excluded_student.sql
Labels: 👾bug

#848 merge: (#827) 모범 학생 후보 제외 학생 제거 api 생성
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/exception/VoteExceptions.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/exception/error/VoteErrorCode.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/service/CommandVoteService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/service/CommandVoteServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/service/GetVoteService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/service/GetVoteServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/spi/CommandExcludedStudentPort.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/spi/QueryExcludedStudentPort.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/usecase/DeleteExcludedStudentUseCase.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfig.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/vote/ExcludedStudentPersistenceAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/vote/VoteWebAdapter.kt
Labels: feat

#854 merge: (#853) Security Config 추가
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfig.kt
Labels: 👾bug

#858 merge: (#857) VotingTopic 생성 시 id를 리턴하도록 변경
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/dto/response/CreateVotingTopicResponse.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/usecase/CreateVotingTopicUseCase.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/vote/VoteWebAdapter.kt
Labels: feat

#859 merge: (#856) excludedStudent를 제외하는 쿼리 추가
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
Labels: feat
