Repository team-aliens/DMS-Backend, pull requests merged in 2025-04, with the labels that each got.

#862 merge: (#861) VoteWebAdapter 수정
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/vote/VoteWebAdapter.kt
Labels: 👾bug

#865 merge: (#864) SecurityConfig 수정 및 학교 ID 조회 방식 변경
  dms-core/src/main/kotlin/team/aliens/dms/domain/student/service/GetStudentServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/student/spi/QueryStudentPort.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfig.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/student/StudentWebAdapter.kt
Labels: refactor

#872 merge: (#871) Security Config 추가
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfig.kt
Labels: feat

#870 merge: (#869) ExcludedStudent 초기화 로직 추가
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/service/CommandVoteService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/service/CommandVoteServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/spi/CommandExcludedStudentPort.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/usecase/DeleteAllExcludedStudentsUseCase.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/scheduler/ExcludedStudentScheduler.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/vote/ExcludedStudentPersistenceAdapter.kt
Labels: feat

#875 merge: (#874) 모범학생 제외학생 추가 수정
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/usecase/CreateExcludedStudentUseCase.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/vote/mapper/ExcludedStudentMapper.kt
Labels: 👾bug

#868 merge: (#863) 찬반 투표 생성시 투표 항목 자동 생성
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/usecase/CreateVotingTopicUseCase.kt
Labels: feat

#866 merge: (#860) 고아 객체 발생 방지
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/dto/response/CreateVotingTopicResponse.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/service/CommandVoteService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/service/CommandVoteServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/spi/CommandVotePort.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/usecase/DeleteVoteUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/usecase/DeleteVotingOptionUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/usecase/DeleteVotingTopicUseCase.kt
  dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfig.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/vote/ExcludedStudentPersistenceAdapter.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/vote/VotePersistenceAdapter.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/vote/repository/VoteJpaRepository.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/vote/repository/VotingOptionJpaRepository.kt
  dms-presentation/src/main/kotlin/team/aliens/dms/domain/vote/VoteWebAdapter.kt
Labels: 👾bug

#873 merge: (#844) 투표 결과 조회 쿼리 모범학생, 학생 분리 및 관련된 기능 전체 수정
  dms-core/src/main/kotlin/team/aliens/dms/domain/notice/service/CommandNoticeServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/service/GetVoteService.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/service/GetVoteServiceImpl.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/spi/QueryVotePort.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/usecase/QueryVotesUseCase.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/usecase/UpdateVotingTopicUseCase.kt
  dms-persistence/src/main/kotlin/team/aliens/dms/persistence/vote/VotePersistenceAdapter.kt
Labels: feat, refactor

#877 merge: (#876) studentId -> id 로 변경
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/dto/response/VoteResponse.kt
  dms-core/src/main/kotlin/team/aliens/dms/domain/vote/usecase/QueryAllExcludedStudentUseCase.kt
Labels: refactor
